### ISSUE TITLE
【必须】【一般】弹框中的话术是否符合蓝鲸设计规范？已确定规范是：确认重载所选主机的配置？

### ISSUE THREAD

**Issue by XiaoE0203** [TencentBlueKing/bk-nodeman#1084]
![image](https://user-images.githubusercontent.com/54015094/191013080-3cb6c955-fbef-4c9d-b03f-e08367f42027.png)

**Comment by ZhuoZhuoCrayon** [comment]
改为："确认重载所选主机的配置？"
