### ISSUE TITLE
【必须】【一般】编辑配额页面,返回后,左侧的业务由全业务变成了单个业务,很突兀.

### ISSUE THREAD

**Issue by XiaoE0203** [TencentBlueKing/bk-nodeman#1088]
![image](https://user-images.githubusercontent.com/54015094/191013812-30ea293c-2fb9-4870-99a2-a0be6a9288a5.png)
![image](https://user-images.githubusercontent.com/54015094/191013844-e521bd17-e74f-442b-a94a-a7f07e877c7c.png)
![image](https://user-images.githubusercontent.com/54015094/191013870-815ae0e4-a3f6-4d4e-9898-de9b62a7fc93.png)

**Comment by ZhuoZhuoCrayon** [comment]
暂时没有复现，daoqing 看看，没复现就关了
