### ISSUE TITLE
【必须】资源配额-配额百分比例含义不明确

### ISSUE THREAD

**Issue by XiaoE0203** [TencentBlueKing/bk-nodeman#1093]
配额，10%是所有插件占用10%，还是每个插件占用10%
10%是总体CPU的10%，还是单核10%
需要添加说明文案，予以明确
![image](https://user-images.githubusercontent.com/54015094/191014830-dbf59aaa-89ac-4ee5-95d3-c7e9e07b99ff.png)

**Comment by ZhuoZhuoCrayon** [comment]
改下 tooltip 信息：
CPU 配额：每个插件 CPU 使用率上限百分比（总占比，非单核占比）
内存配额：每个插件内存使用率上限百分比
