### ISSUE TITLE
【必须】【bug】为什么卸载需要手动操作? 而且也没地方指导如何手动卸载.

### ISSUE THREAD

**Issue by XiaoE0203** [TencentBlueKing/bk-nodeman#1100]
![image](https://user-images.githubusercontent.com/54015094/191015983-2405472a-0e17-4448-abe2-3356dcd69ea5.png)

**Comment by CohleRustW** [comment]
解决方案一：
  - 前端卸载动作接口不再使用手动安装参数，关闭手动卸载入口

解决方案二：
  - 排期处理安装方式历史覆盖问题
  - 设计上区分手动卸载与远程卸载
  - 获取安装命令接口兼容卸载场景
