### ISSUE TITLE
【必须】【一般】我卸载了一个agent, 然后在节点管理依旧存在记录, 如何删除?  请排查环境是否有人同时操作

### ISSUE THREAD

**Issue by XiaoE0203** [TencentBlueKing/bk-nodeman#1101]
![image](https://user-images.githubusercontent.com/54015094/191016108-2248e1c7-d1e0-445a-b4f5-6646dc38778b.png)
![image](https://user-images.githubusercontent.com/54015094/191016196-0e8f625e-bc41-4e79-a966-f1180493c6ff.png)
![image](https://user-images.githubusercontent.com/54015094/191016277-abe028c0-10f0-4b95-8881-f702675f4b76.png)
![image](https://user-images.githubusercontent.com/54015094/191016319-c8e5c853-a4eb-4abc-80bb-dce0ed008380.png)
![image](https://user-images.githubusercontent.com/54015094/191016370-b88a079a-5e24-4614-97e2-dc99068cb433.png)

**Comment by ZhuoZhuoCrayon** [comment]
没有复现
