### ISSUE TITLE
[BUG] 2.0 Agent 注册及健康检查上报错误信息缺失

### ISSUE THREAD

**Issue by ZhuoZhuoCrayon** [TencentBlueKing/bk-nodeman#1180]
**问题描述**
2.0 Agent 注册及健康检查上报错误信息缺失

**重现方法**
1. 安装 Agent 或 Proxy
2. 让 register / healthz 报错

**预期现象**
把报错信息上报到后台，例如：xxx failed：xxxx

**截屏**
![WeChatWorkScreenshot_4f39a793-ccb9-43f8-b949-e57861e6d10e](https://user-images.githubusercontent.com/42019787/197098529-618ccc78-8a0a-4c15-851f-c790330c9d3c.png)

**请提供以下信息**

 - [x] bk-nodeman   版本 (发布版本号 或 git tag)： 
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk-nodeman 异常日志：

**Comment by CohleRustW** [comment]
同时处理的问题：
1. ``JOINT_DEBUG_SWITCH``联调开关下线
2. 上报错误
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/40767043/199383628-7a6623fd-f3b9-4e67-8d3b-065662e92762.png">
