### ISSUE TITLE
[BUG] 更新 Proxy 密钥所保存的密钥信息有误

### ISSUE THREAD

**Issue by ZhuoZhuoCrayon** [TencentBlueKing/bk-nodeman#1339]
**问题描述**
更新 Proxy 密钥所保存的密钥信息有误

**重现方法**
1. 成功安装一个 Proxy（用 rsa 密钥）
2. 更新该 Proxy 的密钥信息
3. 重新安装
4. 报错：认证信息有误

![企业微信截图_874fed19-d79e-4576-b0f5-812c2605a272](https://user-images.githubusercontent.com/42019787/207829183-500b0955-ec8f-48b8-bc8b-5f96a8f7351e.png)

**预期现象**
准确更新密钥，实际在 admin 后台看保存的密钥变成了 object[object]

**截屏**
请提供截屏来解释你的问题，当然这也能更好地帮助我们理解问题。

**请提供以下信息**

 - [x] bk-nodeman   版本 (发布版本号 或 git tag)： 
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk-nodeman 异常日志：

**Comment by CohleRustW** [comment]
<img width="2656" alt="image" src="https://user-images.githubusercontent.com/40767043/209660682-e1df16c9-726f-4882-9d0d-c86f0fbd5773.png">

接口: `host/update_single/`

需要前端介入处理 @GONGONGONG
