### ISSUE TITLE
[OPTIMIZATION] 支持日志状态表的删除

### ISSUE THREAD

**Issue by ZhuoZhuoCrayon** [TencentBlueKing/bk-nodeman#1348]
**你想要什么功能**
支持日志状态表的删除，删除后不影响页面/API查看任务状态

**为什么需要**
避免该表的过度膨胀

**建议如何实现**

日志状态表：`SubscriptionInstanceStatusDetail`

配置：是否定期清理日志，仅保留xx天的日志，保留什么级别的日志，由于存量日志过多，每次最多删除xx条
指引：危机时刻删表、按时间戳删除历史日志（保留xx天）

**Comment by ZhuoZhuoCrayon** [comment]
## 实现思路

### 目标
* 删除 `SubscriptionInstanceStatusDetail`，`SubscriptionInstanceRecord` 的 `status` 不会被重置
* 任务历史，子步骤状态可以处于 PENDING
* 订阅（采集） & 页面相关的依赖接口不能有报错

### 可能需要调整的地方

`apps/backend/subscription/task_tools.py`

1. 保留失败日志的情况下，确保可以通过仅存的失败节点，还原之前的节点状态

![企业微信截图_b612f5de-f102-409b-8881-5678b423c0d2](https://user-images.githubusercontent.com/42019787/228720092-698af9e5-34d7-4a75-9d9f-95b802c0cf72.png)


2. `SubscriptionInstanceRecord` 有明确状态的情况下，如果 `collect_status` 处于 `PENDING`，填充 `SubscriptionInstanceRecord` 自身的状态及时间

![企业微信截图_d6c4eb2b-2c87-4671-be3a-6c59f2fd0876](https://user-images.githubusercontent.com/42019787/228720220-918acd51-0990-401d-b629-6be6972c6056.png)

**Comment by CohleRustW** [comment]
## 方案实现事项

- 周期任务清理订阅日志表
  - 尽量根据索引和时间段进行删除，避免非索引字段条件进行`DELETE`
 


#### 注意事项


1. 清理`SubscriptionInstanceStatusDetail`时避免全表扫描
2. 保持`status` 和 `status_display` 统一
3. 对保留指定日志级别的任务注意还原前节点状态

#### 紧急清理表方案

1. 指引`Truncate`表方案
2. 指引周期任务配置方案

**Comment by ZhuoZhuoCrayon** [comment]
## 交付目标

### 文档
数据删除的操作指引

### 自测截图
> Pipeline 相关的表默认删除，删除的表参考：`apps/backend/management/commands/clean_old_instance_record.py`
> 删表操作执行后，需要删表时间点之后的 SubscriptionInstanceRecord 数据强制失败，避免后续巡检报执行中的错误
> 以下每个功能自测点附上截图，作为后续给出方案及效果的一部分

#### SubscriptionInstanceStatusDetail 全表删除
* SaaS - 执行历史允许「步骤」级别的状态不准确，但「主机执行状态」（SubscriptionInstanceRecord）要准确
* 订阅 - 巡检/重试不受影响
* 订阅 - instance_status / statistic / task_result_detail / task_result 不报错，主机执行状态准确

#### 保留 SubscriptionInstanceStatusDetail ERROR 日志
* SaaS - 执行历史允许「步骤」级别的状态不准确（失败节点日志可查），但「主机执行状态」（SubscriptionInstanceRecord）要准确
* 订阅 - 巡检/重试不受影响
* 订阅 - instance_status / statistic / task_result_detail / task_result 不报错，主机执行状态准确，失败节点日志可查

#### 保留 SubscriptionInstanceStatusDetail 某个时间后的数据
* 日志保留时间之外：同 SubscriptionInstanceStatusDetail 全表删除
* 日志保留时间之内：各项功能需正常

**Comment by CohleRustW** [comment]
# 自测截图

## 清理数据前
<img width="2283" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/6d48b650-5432-4b69-917e-18207a8a2cd4">
<img width="2246" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/39c004ff-dcb3-4890-9fe9-49fe2ceaf69c">
<img width="2261" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/0fdf9138-83c1-4598-a8a8-16c030045c9c">

## 清理所有日志
<img width="587" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/9549d94d-ad19-4b1e-a51c-57542ef9b0b9">
<img width="2291" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/79cf42c0-b2af-47af-a471-4cc9aeffd074">

<img width="2294" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/5474d018-bbdc-415b-ad01-67d07d42d92b">
<img width="1518" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/22b2b924-3d2d-42c1-b222-bf9b2d3c2ae0">
<img width="1217" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/276210e8-7d2e-4f8e-b00d-c3666295ba3c">
<img width="1113" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/13c1b864-d72d-4c2c-b94e-120e7b28d069">
<img width="1148" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/e27d2fbf-045e-4bec-a3e8-c9980955c64b">
<img width="1728" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/484036dc-ab5d-4e46-8cf9-472d12a52c20">


## 保留失败日志

<img width="504" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/d9327e8c-a08a-481d-9955-cb8ac0571296">
<img width="919" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/f6fa963c-0284-455f-be00-2e1f3a11490d">
<img width="2279" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/73ecbc5b-59a1-4d34-8ab4-aa0f751ec5db">
<img width="1607" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/59b4285b-00be-4a68-9569-00b0d24688b8">

<img width="2291" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/404779f2-61a5-4aac-8cd5-c52e1ca08d88">
<img width="1866" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/d99e5b99-0abb-4e04-b317-c28161c60e7c">
<img width="2571" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/32a1a06e-d427-48b7-9c19-a8298dae39b4">
<img width="1504" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/690ad686-b904-49e7-b958-e212ebe2e315">

**Comment by CohleRustW** [comment]
## 订阅巡检
1. 启用订阅巡检
<img width="610" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/c1bb4b13-4283-403c-89c6-5fdf45d29410">

2. 查询订阅 `task` 
<img width="2362" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/b9e83313-faee-409d-ab01-8c30e1ca851c">

3. 执行巡检任务
<img width="862" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/8ea79267-4eb8-47ef-b59d-7ecebbf73564">

4. 查询巡检订阅 `TASK`
<img width="2151" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/d7cbff58-69e8-4305-b085-539a1325a2b4">

5. 相关接口执行结果验证
<img width="1340" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/0428711e-f61f-48be-91ba-3741caa080b8">
<img width="1401" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/38963577-da6e-416f-b504-0b29370fedcb">
<img width="1639" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/2872b092-4580-4eed-8e8a-bff479fc57da">

**Comment by CohleRustW** [comment]
## 删除指定时间之前的日志
<img width="1035" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/81350dcf-f341-4996-9b30-77feef3314f7">
<img width="453" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/af112f89-b7f8-4c88-af13-41149893aba5">

<img width="1679" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/240d54c3-3ddd-42eb-a060-82f2fd987c98">
<img width="1671" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/44b33b4c-29fd-4176-832f-32bde5a112c5">
<img width="971" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/fdfe80f3-b61d-47bd-a434-21780d1b68ef">
<img width="1418" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/fff72ac0-5037-4d85-a592-8b5b6e6c0804">

**Comment by ZhuoZhuoCrayon** [comment]
![企业微信截图_dd9e0ff9-b69f-4230-a037-2c5182695c76](https://github.com/TencentBlueKing/bk-nodeman/assets/42019787/9fb14c40-daea-44f1-bbee-27ae8710ceb5)


本意是想压缩存储节点，但漏了 {"SUCCESS", "PENDING"} 这种状态组合，在这种情况下，会偶发任务提前成功的现象


模拟该情况：

![企业微信截图_47d6f53b-cfb6-4dc0-ac56-9e30fe9a1434](https://github.com/TencentBlueKing/bk-nodeman/assets/42019787/4b55317a-73de-40c7-8318-2ce9d582dbf4)


保留失败日志：

![企业微信截图_9cfbd545-9db7-436c-879b-8f5b7a7fa9a5](https://github.com/TencentBlueKing/bk-nodeman/assets/42019787/fbea41e7-ddcb-41f0-94f7-9c4e998b2cc0)
