### ISSUE TITLE
[FEATURE] Proxy 安装适配 CentOS 8 / Ubuntu

### ISSUE THREAD

**Issue by ZhuoZhuoCrayon** [TencentBlueKing/bk-nodeman#1405]
**你想要什么功能**

Proxy 安装适配 CentOS 8

**为什么需要**

「CentOS 8」py36 版本缺少 so 文件

![企业微信截图_0e0960dd-4dab-4957-b86e-1a291efae4d0](https://user-images.githubusercontent.com/42019787/211238928-163bb369-121f-4cd7-a2bc-1c1ac96b90bc.png)

「Ubuntu」
<img width="556" alt="企业微信截图_75d50d9f-d673-4e67-a08c-1efee851abbc" src="https://user-images.githubusercontent.com/42019787/211733340-3141d619-1c16-4946-819b-1bb150d38b0c.png">

**建议如何实现**

**Comment by CohleRustW** [comment]
## 自测
1. `Centos 8 `未安装场景
<img width="1463" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/75874144-ec7d-4d8c-aa51-6eeb37cee3c2">

2. `Centos 8`已安装场景
<img width="885" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/0132433b-98fe-4462-bbab-15a7b5bde981">

3. `Centos 7` 未安装场景
<img width="945" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/b16f98c6-4f8d-4a6f-b1be-eee59628305b">
