### ISSUE TITLE
[FEATURE] 同步 CMDB 主机 cpu 架构及操作系统信息

### ISSUE THREAD

**Issue by pagezz-canway** [TencentBlueKing/bk-nodeman#1454]
**你想要什么功能**
节点管理同步CMDB主机信息时带上主机的CPU架构信息

**为什么需要**
我们有大量信创aarch64服务器（linux操作系统）需要纳管，由于环境限制，只能采用手动脚本安装agent后再导入cmdb的方式进行纳管。采用该方式无法在安装时注册CPU架构信息到节点管理，后续进行插件管理时产生了问题，下发的插件包均为x86架构。
因为已经有大量这种机器手动安装了agent，且后面也有很多同样的机器只能手动纳管。需要有自动更新CPU架构的功能，即节点管理同步CMDB主机信息时带上主机的CPU架构信息

首次通过节点管理安装的aarch64服务器，是能识别架构的。

**建议如何实现**
当前版本号：2.2.11
如上。

**Comment by ZhuoZhuoCrayon** [comment]
### CPU 架构

1. 需要确认 CMDB cpu 架构是否完全准确：

2. 做成开关的形式，默认关闭同步功能
* 开关通过 `GlobalSettings` 维护，同步主机时实时获取配置，参考：[GlobalSettings 维护](https://github.com/TencentBlueKing/bk-nodeman/blob/b48b159ba60c2072da5930b6a6b332fc2ca10b91/apps/node_man/models.py#L114)

3. 可能需要修改 & 完善的地方：
* `HostV2Tools.get_cpu_arch` - https://github.com/TencentBlueKing/bk-nodeman/blob/b48b159ba60c2072da5930b6a6b332fc2ca10b91/apps/node_man/tools/host_v2.py#L49
* CMDB 空值处理，如果从 CC 拿不到 CPU 架构信息，走原来的逻辑


### 操作系统

1. 背景：现在同步操作系统优先使用 `bk_os_name` 模糊识别操作系统类型，在重装系统场景下，`bk_os_name` 不一定会主动更新，导致同步的操作系统类型不准确
* 参考 `HostV2Tools.get_os_type` - https://github.com/TencentBlueKing/bk-nodeman/blob/b48b159ba60c2072da5930b6a6b332fc2ca10b91/apps/node_man/tools/host_v2.py#L20

2. 新增功能：可以通过配置（`bool` 值），控制操作系统类型的同步字段优先级
* 默认：保持原逻辑
* 否则：先根据 `bk_os_type` 再根据 `bk_os_name`

**Comment by neko12583** [comment]
# 从 `CMDB` 同步主机架构

## `CPU` 架构

### 开关

在 `GlobalSettings` 中添加配置 `SYNC_CPU_ARCH_BY_CMDB`，默认为 `false`

如果 `SYNC_CPU_ARCH_BY_CMDB` 为 `false` 或缺省时，走原有逻辑，从 `DEFAULT_OS_CPU_MAP` 中根据操作系统获取默认 `CPU` 架构

如果 `SYNC_CPU_ARCH_BY_CMDB` 为 `ture` 时，同步主机数据字段列表 `CC_HOST_FIELDS` 中追加 `bk_cpu_architecture` 同步字段

### 数据对接

`cmdb` 中主机架构字段 `bk_cpu_architecture` 枚举值目前只有 `x86` 、 `arm` ，且节点管理中区分 `x86_64`、`x86`

- 如果为 `x86` ，对 `cmdb` 数据中 `bk_os_bit` 进行模糊匹配是否包含 "32" 字符串，是则为 `x86`，否则为 `x86_64`
- 关键词不一致，`cmdb` 为 `arm` ，节点管理为 `aarch64`，需要做一层转换，维护一个 map
- `bk_cpu_architecture` 字段为空，走原有逻辑

## 操作系统

### 开关

在 `GlobalSettings` 中添加配置 `OS_TYPE_PRIORITY`，默认为 `false`

如果 `OS_TYPE_PRIORITY` 为 `false` 或缺省时，走原有逻辑，优先根据 `os_name` 模糊匹配

如果 `OS_TYPE_PRIORITY` 为 `ture` 时，优先根据 `os_type` 模糊匹配


纠结点：存量主机 CPU 架构是否更新

结论：更新

默认主机注册的 CPU 架构是 X86，CPU 位数是空 -> 不更新，可能是节点管理刚安装注册到 cc 的机器，触发同步事件，先让子弹飞一会，等后续采集器安装了，把架构信息报到 CMDB 再同步
X86，CPU 架构不为空 -> 更新
ARM -> 更新为 arrch64

**Comment by ZhuoZhuoCrayon** [comment]
自测

开启 CPU 架构同步
1. 删除本地全部主机，将 CC 的部分主机修改为不一样的架构：可以正常同步
2. 新增主机，可以同步到新增的主机
3. 删除主机，可以删除
4. 更新 CMDB 主机属性（CPU 架构、主机名称），可以正常同步

不开 CPU 架构同步
1. 将 CC 的部分主机修改为不一样的架构，不更新架构信息
2. 新增主机，可以更新为操作系统对于的默认 CPU 架构

操作系统名称优先
1. 优先匹配操作系统名称

操作系统类型优先
1. 优先匹配操作系统类型

**Comment by neko12583** [comment]
开启CPU架构同步
![开启同步cmdb主机架构](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/e7bb4594-e60b-456f-89a2-da55b097f237)
删除本地全部主机
![删除本地所有主机](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/008891c9-102a-4a1c-a657-77500279141c)
将 CC 的部分主机修改为不一样的架构
![修改cmdb主机架构为arm](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/6fe08e3c-5d6e-4dd6-8a48-c5c65c46c81e)
可以正常同步
![修改cmdb主机架构同步](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/78891808-eafe-4874-b111-0c9b42440d1c)

**Comment by neko12583** [comment]
新增主机
![cmdb新增主机](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/75959d6d-1c08-4190-b2bf-342f25b9aacf)

可以同步到新增的主机
![同步cmdb新增主机](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/f0d75e07-9b0e-4ea5-989b-69a53005e54b)

**Comment by neko12583** [comment]
新增主机
![cmdb新增主机](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/26bf14ca-6843-4612-9287-3e43806f984b)

可以同步到新增的主机
![同步cmdb新增主机](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/ab04b276-89e8-495b-ba3d-7104621f0f80)

**Comment by neko12583** [comment]
删除刚新增的主机
![删除cmdb主机](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/54cde908-0dc5-44cc-b7c3-664cc85f6bb7)

可以删除
![同步cmdb删除的主机](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/dc96607b-bc08-40de-a988-a59ede0e6692)

**Comment by neko12583** [comment]
更新 CMDB 主机属性（CPU 架构、主机名称）
![修改cmdb主机信息](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/c4b3ac10-2a22-4970-9d83-0e04e707731d)

可以正常同步
![同步cmdb修改主机信息](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/2d6d83f4-501a-40d1-8938-4b365895c4a7)

**Comment by neko12583** [comment]
不开 CPU 架构同步
![关闭开关](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/d538ee67-d5e3-4d15-aa48-f4303143f796)

将 CC 的部分主机修改为不一样的架构
![关闭开关修改cmdb架构](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/3e32a0f0-58a8-4616-80ed-82274369b67a)

不更新架构信息
![关闭开关架构不同步](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/100aacae-1729-428e-9168-789a25bd48ac)

新增主机
![新增主机arm](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/f1efcb72-7828-4bc8-a9a0-7ec77ddfbd3e)

可以更新为操作系统对于的默认 CPU 架构
![同步默认架构](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/daeb0589-d28c-4855-a390-52a9af46ad3c)

**Comment by neko12583** [comment]
修改cmdb数据，使操作系统类型与操作系统名称不匹配
![修改cmdb操作系统](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/8baacfa3-7eee-4b5e-b8bf-62d493f3fa8e)

打开开关，操作系统类型优先
![操作系统优先开关](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/8d87085f-b081-42af-934b-d1c05632d475)

优先匹配操作系统类型
![优先同步操作系统类型](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/32e98763-3ef6-458b-bd5c-0e0b702ebbf4)

关闭开关，操作系统名称优先
![关闭类型优先开关](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/3791ab4a-6569-4a0c-abc2-96fc9f2e8a5e)

优先匹配操作系统名称
![操作系统名称优先](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/06f3259c-2dfe-48b8-8dbb-01a08fe2cd7c)
