### ISSUE TITLE
[FEATURE] 提供主动触发异步任务的机制

### ISSUE THREAD

**Issue by ZhuoZhuoCrayon** [TencentBlueKing/bk-nodeman#1473]
**你想要什么功能**
提供主动触发主机同步的机制

**为什么需要**
主机同步延迟兜底

**建议如何实现**

1. 使用 celery 的 `delay` 机制，封装 `sync_cmdb_host_periodic_task` 作为异步任务
2. 异步调用及任务完成度查询，可参考：https://github.com/ZhuoZhuoCrayon/djangocli/blob/0.5.x/apps/example/handler.py
3. 封装通用的异步任务调用和查询接口到后台 backend 模块，`sync_cmdb_host` 作为现阶段仅支持的可选项
4. 前端界面提供主机同步按钮

**Comment by ZhuoZhuoCrayon** [comment]
简单写下实现方案（大致改哪些东西）

**Comment by neko12583** [comment]
## 数据库

为控制任务执行频率，避免用户无限制发起任务，储存 task_id 查询任务结果

记录 任务发起人、任务id、任务名称、任务参数、创建时间、状态

当接收到发起新同步任务请求时，存在同步主机任务正在运行，抛出异常

程序自主发起同步主机业务时，任务发起人为 system

## 权限

校验用户是否拥有对应业务的权限

同步 cmdb 主机最小可对单一业务的主机进行同步，同步之前判断用户是否具有该业务的操作权限

同步任务业务范围为全部时，其中存在没有权限业务，抛出异常

## 封装任务模块

将同步主机任务封装为异步任务，主动触发同步主机任务与周期同步主机任务分别调用该异步任务

结构：
```
sync_task
|__serializers.py  # 控制入参, 目前任务可选项为 sync_cmdb_host
|__views.py  # 处理 request 请求
|__handler.py  # 封装通用逻辑
|  |__def create_task(created_by, bk_biz_id, task_name)
|  |__def task_result(task_id)
|__manager.py  # 管理任务名称与任务函数对应关系
|  |__class SyncTaskManager
|     |__def sync_cmdb_host(bk_biz_id)
|__tasks.py  # 封装异步函数
   |__def sync_cmdb_host_task(bk_biz_id=None)
```

**Comment by ZhuoZhuoCrayon** [comment]
@neko12583 
数据库：celery 有提供 task_id 及查询功能，**无需**建表存储，具体参考：https://github.com/ZhuoZhuoCrayon/djangocli/blob/0.5.x/apps/example/handler.py

manager 和 task 的功能好像重复了

发布该 API：
1. 由于用到 celery，需要在 SaaS 再封一层接口，用于调用后台 sync_task，具体可以参考现在 `NodeApi` 的调用方式

2. 发布 API（接入 ESB / APIGW） 方式参考：docs/workflows/release/api/readme.md，这块由 @CohleRustW 跟进



当接收到发起新同步任务请求时，存在同步主机任务正在运行，抛出异常
这里可以更优雅的处理，建议构造一个任务键，例如 `{settings.APP_CODE}:backend:sync_task:sync_cmdb_host:biz:xx`，用于存当前处于执行的 task_id，在任务执行完成后删除，在执行期间如果有新的同步请求，返回 Redis 记录的 task_id 即可。这个键要设置一个过期时间，例如 10s，避免异常情况下键不删除
