### ISSUE TITLE
[FEATURE] 提供导入导出工具及指引

### ISSUE THREAD

**Issue by ZhuoZhuoCrayon** [TencentBlueKing/bk-nodeman#1487]
## 你想要什么功能
提供导入导出工具及指引

## 为什么需要

其他环境的资源信息，导入到某个环境，在这个过程中，第三方系统/自身系统 `id` 信息会发生变更，需要提供工具，基于新老环境 `id` 映射关系对新环境的导入数据进行初始化/校准操作。

对于节点管理，在这个过程中涉及：
* 云区域：CMDB 导入已将数据同步到新环境，节点管理同步即可，但云区域的 Proxy / 接入点信息由节点管理维护，需要将老环境信息基于 CMDB 的云区域 ID 映射、业务 ID 映射关系，给新同步到的「主机信息」标识是否 Proxy 及接入点（ap_id）、「云区域信息」标识接入点（ap_id）
* 自定义插件：由监控用户制作，需要将这部分插件导入到新环境

### 导出

1. Proxy 信息表：基于 Host 表导出即可
2. 云区域-接入点信息表：基于 Cloud 表导出即可
3. 监控平台制作的插件，一般位于 `/upload` 目录下

导出脚本的可选形式：由于导出环境大部分是老版本的节点管理，不能通过 manage.py 的脚本，这块建议提供 `sql` 的方式导出数据

数据文件格式：导出的数据要作为导入脚本的参数，这里可选 csv 等可解析的格式

![企业微信截图_a5fa94bd-bc3b-4de1-af63-c6f43bb84738](https://user-images.githubusercontent.com/42019787/227133270-c9f23419-3c45-451b-86e2-1e8108350215.png)

### 导入

数据依赖
* CMDB 的业务、云区域映射数据：系统导出导入后，会把变更数据写到公共DB，这里需要通过DB信息，通过连接 MySQL 获取这部分的数据
* 节点管理自导出的数据
* 接入点映射数据：这部分通过对比新老环境可以获得，是一个 dict，例如 {1: 1, 2: 3}

参数
* 是否迁移 Proxy：如果不迁，就不需要标记 Proxy 了
* 业务 ID 列表

要做什么
* 把 Proxy 和 云区域的接入点信息改对，可能需要（将 Proxy 的登录 IP / extra 部分信息拷过来）：比如老环境导入新环境后， 业务ID（101 -> 201），云区域 ID（1 -> 11），内网 IP 不变，那么 Proxy 信息就会从老环境的（101, 1, IP）变为新环境的（201, 11, IP），通过上述的映射关系，就可以找到需要被标记为 Proxy 的机器。
* sync_cmdb_host 支持指定业务列表同步
* init_offical_plugins 需要验证是否支持第三方插件的导入，并参考 https://github.com/TencentBlueKing/bk-nodeman/blob/v2.3.x/support-files/kubernetes/helm/bk-nodeman/templates/NOTES.txt 的插件包导入部分，将插件包目录 mv 到容器，并执行命令批量初始化插件包的指引

![企业微信截图_f961271a-b803-4d7e-9bc5-b7c2fbed248d](https://user-images.githubusercontent.com/42019787/226913674-81362465-01f8-40ce-996a-5d53b97baf7d.png)

## 如何推进

1. 阅读上述需求及建议的实现
2. 在 issue 中列出具体的实现方案（数据导出方案，映射替换实现方案）
3. 实现
4. 导入导出的操作文档

**Comment by CohleRustW** [comment]
# 方案预览
- 增加`load_or_export_host_info`  `command`
## 导出
### Proxy 信息表
- 导出文件格式`csv`，当前环境的所有`proxy`主机全部导出到同一份文件，导出为
`bk_biz_id`  `bk_cloud_id` `bk_inner_ip` `data_ip`  `extra_info`

### 云区域-接入点信息表
- 导出文件格式`csv`  `CLOUD`表全字段导出

## 导入
### 配置文件
- `YAML` 配置方式，增加数据库相关的配置项用于链接公共DB数据库
- 增加是否导入`proxy` 的cmmand 参数
- 增加接入点映射数据对照配置，预期是字典 {1:20}

### 导入逻辑

- 链接公共DB数据库获取 业务和云区域的映射关系
- 获取导出的文件内的数据，并根据配置的接入点对照关系修改主机的接入点信息，根据映射关系导入当前数据库
- 如果不迁移 Proxy , 就不把对应业务的proxy导入当前环境，只负责修改对应环境下指定业务的proxy主机的相关信息，不导入已经导出的主机

**Comment by ZhuoZhuoCrayon** [comment]
`并根据配置的接入点对照关系修改主机的接入点信息，根据映射关系导入当前数据库`
* 问题1：主要是修改 Proxy / 云区域 的接入点
* 问题2：这里导入数据库指的是什么数据导入？

`只负责修改对应环境下指定业务的proxy主机的相关信息`
* `sync_cmdb_host` 已经把主机同步到新环境了，这里还需要修改什么数据吗


需要继续补充：`映射替换实现方案` - 如何根据已有的 id 映射关系，将数据替换对？

**Comment by CohleRustW** [comment]
<img width="2007" alt="image" src="https://user-images.githubusercontent.com/40767043/230542441-82fac987-42e6-4d10-8e24-5a05c1bb8ef4.png">
