### ISSUE TITLE
[FEATURE] 导航规范

### ISSUE THREAD

**Issue by GONGONGONG** [TencentBlueKing/bk-nodeman#1501]

**Comment by ZhuoZhuoCrayon** [comment]
目标：以环境变量形式，在部署阶段注入，并提供给前端

1. 环境信息
复用 `BKAPP_RUN_ENV`
* `ieod` - 正式 / 出海
* `ce` - 社区/私有化

2. 开源社区链接 - `BKAPP_NAV_OPEN_SOURCE_LINK`
3. 联系 BK 助手 / 技术支持 - `BKAPP_NAV_HELPER_LINK`
* 前端根据 `BKAPP_RUN_ENV` 选择展示文案

后台新增环境变量方法，参考这个 PR：https://github.com/TencentBlueKing/bk-nodeman/commit/6707d1ad3b071dbc5f4c5085f2b2369619487f23
