### ISSUE TITLE
任务历史支持IP过滤

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-nodeman#1631]
<img width="2485" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/19284021/703c233d-3c16-491e-a93b-1f712f936baf">

支持通过多个IP搜索任务历史

**Comment by neko12583** [comment]
# 方案

## 接口

查询任务列表：api/job/job_list/

增加参数 `inner_ip`，为列表类型：

```python
inner_ip = ["127.0.0.1", "::1"]
```

## 针对 `ip` 进行筛选

如果携带 `inner_ip` 参数

在该接口原查询逻辑结束、分页前，对 `node_man_job` 表数据中所有 `task_id_list` 提取为 `all_task_id_list`，同时构建字典用于后面查询：

```python
{
    "job_id": [task_id_list]
}
```

判断每个 `ip` 是 `IPv4` 还是 `IPv6` 分开组合成查询 `node_man_host` 条件

从 `node_man_host` 查出 `IPv4 in inner_ip` 、`IPv6 in inner_ipv6` 的 `bk_host_id、bk_cloud_id`

根据信息生成 `instance_id` 查询范围 `instance_id_list`，两种形式：`host|instance|host|{bk_host_id}`、`host|instance|host|{ip}-{bk_cloud_id}-{constants.DEFAULT_SUPPLIER_ID=0}`

从 `node_man_subscriptioninstancerecord` 中查询 `task_id in all_task_id_list`、 `instance_id in instance_id_list`

## 其他
在联调环境：`https://paas-dev.bktencent.com/` 中，`node_man_subscriptioninstancerecord` 表数据量为：15461906

![联调环境实例记录表数据量](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/dc1dda09-5fe4-4cb6-a77d-defe7dbd24ac)
直接查询 `instance_id` 字段值模糊搜索包含指定 `ip` 耗时为：15s
![联调环境实例记录表模糊搜索](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/3e61ea26-77d9-49c7-a794-a38e631073fc)
查询时指定 `instance_id` 字段区间耗时为：0.03s
![联调环境指定实例id区间](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/a70cd8fd-c6d2-401f-a96c-4897e45ea7d3)
查询时同时指定 `instance_id` 字段区间与 `task_id` 区间耗时为：0.01s
![联调环境指定任务id和实例id](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/d5a597eb-a846-4ed8-ba51-23ac995fcd54)

**Comment by neko12583** [comment]
## 方案更改
在 `node_man_subscriptioninstancerecord` 表中根据 `instance_id in instance_id_list` 以及 `create_time > start_time` 两个条件进行筛选

## 理由
在 `node_man_subscriptioninstancerecord` 表中有 1546w 条数据

![image](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/19873206-e8b1-4d2f-9917-534ab396922c)

大致估算 node_man_job 表每月新增 3w 条数据

分别以 task_id & instance_id 与 create_time & instance_id 两种方式进行查询，对比时间消耗

### 方式 1：task_id & instance_id 
```
from apps.node_man import models
task_id = models.SubscriptionInstanceRecord.objects.filter(id__lt=120000).values_list("task_id", flat=True)
task_id = list(set(task_id))
print(len(task_id))
```

![image](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/59196a37-3fbb-491b-a565-dc1774baea1d)

```
import time
def test_time(params):
    print(time.time())
    data = models.SubscriptionInstanceRecord.objects.filter(**params)
    print(time.time())
    print(len(data))
    return data

params = {"task_id__in": task_id, "instance_id": "host|instance|host|10.0.1.59-0-0"}
data = test_time(params)
```

![image](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/c25eb29c-118f-480c-b547-3c6eda056cb0)

多组数据平均时间为 0.06s

### 方式 2：create_time & instance_id

```
target_date = datetime(2023, 6, 10)
params = {"create_time__gt": target_date, "instance_id": "host|instance|host|10.0.1.59-0-0"}
data = test_time(params)
```

![image](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/ae9b0ff5-0742-49e1-94a4-b7a0c5092696)

多组数据平均时间接近 0.001s

**Comment by neko12583** [comment]
## 自测截图
1、页面显示 ip 搜索条件

![页面显示ip条件](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/c65ca518-dbe6-4490-8941-4cc50a867799)

2、查询指定 ip 任务

![查询ip](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/30d42ad9-ca1b-4843-bb77-68b1b0ad0f30)

3、单个 ip 的任务

![任务详情92](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/cd77802d-4150-4457-9abe-4e5c703aefc6)


4、 多个 ip 的任务

![任务详情多个ip](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/a0671421-21b7-43c6-87e8-a1973c2f5d9b)


5、job 表5000条数据时，且4900都有指定 ip 时，查询shi时间

![数据量5000时响应时间](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/f59559ec-faf3-48f2-9ea0-1149baef637f)

**Comment by neko12583** [comment]
## 问题修复
### 问题复现
当用户不具备全部业务、查询所有业务的历史任务时，会出现报错：
![页面](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/b59adc8a-c2cc-4e6c-8ccd-0823b8658851)
![报错](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/ab9b9993-da63-449c-8d8d-60f64de7b043)

### 问题修复
![修复验证](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/cd26e1c2-c903-44b5-91b1-309b49434472)
