### ISSUE TITLE
[FEATURE]【节点管理-已评审】 安装 Agent 增加数据压缩开关配置

### ISSUE THREAD

**Issue by ZhuoZhuoCrayon** [TencentBlueKing/bk-nodeman#1664]
**你想要什么功能**
安装 Agent 增加数据压缩开关配置

新增配置需求，模板data插件增加数据压缩开关，需要在节点管理页面像DHT的BT开关一样提供用户操作入口，默认关闭

**建议如何实现**

<img width="775" alt="企业微信截图_58842740-75b0-45d5-8b2a-9b52c6db80ff" src="https://github.com/TencentBlueKing/bk-nodeman/assets/42019787/44cd9abc-9569-4721-beab-552d5a8c13c3">

<img width="1052" alt="企业微信截图_e15480f5-f871-4a92-84ca-8d68cd5f17db" src="https://github.com/TencentBlueKing/bk-nodeman/assets/42019787/d26d3515-e06f-47bc-b9d2-db6797f2f661">

**Comment by Shutulee** [comment]
**示例：**
<img width="937" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/50794209/2db8b582-f26f-47b8-8f60-ffa62988dadf">

**Comment by EchoQT** [comment]
数据压缩应该是跟所上报的数据场景有关的吧？
对于一个agent而言，有可能会出现有的数据需要压缩、有的数据不适合压缩的情况吧？
另外，如果用户无需关心，那是否可以自动开启压缩？

总的来说，什么情况需要开启压缩，没说清楚。

**Comment by Shutulee** [comment]
> 数据压缩应该是跟所上报的数据场景有关的吧？ 对于一个agent而言，有可能会出现有的数据需要压缩、有的数据不适合压缩的情况吧？ 另外，如果用户无需关心，那是否可以自动开启压缩？
> 
> 总的来说，什么情况需要开启压缩，没说清楚。

1、开启数据压缩后，所有通过数据管道传输的日志采集数据的流量都将进行压缩，可一定程度上降低数据上报所带来的带宽压力。

2、根据数据场景自动开启压缩的前提是需要知道业务数据内容与格式协议，但agent没法去解析用户的数据，同时支持这个自动的能力开销也较大，可能超过数据压缩的开销本身。
目前的做法是开启后对所有数据进行压缩。不适合压缩的数据执行压缩时，因为本身压缩率没有大的变化开销也不高，和不开启差异不大。

3、影响：会造成少量的CPU占用增加与毫秒级延迟，是agent工作的正常范围内的，但GSE侧不建议默认开启。节点管理产品上会将该影响在tooltips中对用户说明。

**Comment by EchoQT** [comment]
ok

**Comment by ZhuoZhuoCrayon** [comment]
@GONGONGONG ENABLE_DHCP 的场景下，这个字段才给选，类似 IPv6 字段的处理方式
