### ISSUE TITLE
[FEATURE] 后台插件支持配置超时时间

### ISSUE THREAD

**Issue by ZhuoZhuoCrayon** [TencentBlueKing/bk-nodeman#1696]
**你想要什么功能**
后台插件支持超时参数

**为什么需要**
部分逻辑，如 Agent 状态查询，Job 操作实际不需要 6 分钟这么久，希望在某些场景，可以通过调小超时参数，提升用户等待体验，提前暴露问题

**建议如何实现**

范围：Job 相关插件、GetAgentStatusService

apps/backend/components/collections/base.py BaseService -> PollingTimeoutMixin(with polling_timeout in inputs_format)

apps/backend/agent/manager.py 参考 wait 方法，支持传入 polling_timeout

**Comment by neko12583** [comment]
## 方案

### 大概实现逻辑

创建 `PollingTimeoutMixin` 类，`BaseService` 类继承 `PollingTimeoutMixin`

`PollingTimeoutMixin` 中创建 `polling_timeout` 方法，使用 `@property` 进行装饰，提供给子类使用 `self.polling_timeout` 调用

支持可配置超时时间的插件在 `_schedule` 方法中，将取自 `constants.py` 中 `POLLING_TIMEOUT` 改为 `self.polling_timeout`

### 详细实现逻辑

#### `polling_timeout`

`PollingTimeoutMixin` 中 `polling_timeout` 方法从 `GlobalSettings` 中调用 `get_config` 获取 `POLLING_TIMEOUT` 值

默认为 `constants.POLLING_TIMEOUT = 60 * 6`

`GlobalSettings` 中 `POLLING_TIMEOUT` 为字典，可对指定插件对超时时间进行配置：

```python
# {self.component_cls().name: POLLING_TIMEOUT}
POLLING_TIMEOUT = {"get_agent_status": 120}
```

### 自测点

- 不进行配置能够正常安装agent
- 设置 `POLLING_TIMEOUT = {"get_agent_status": 120}` 能够正常安装agent
- 设置 `POLLING_TIMEOUT = {"get_agent_status": 1}` 安装agent会超时失败

**Comment by neko12583** [comment]
## 方案更改
上述方案中，由于作业组件的超时时间在抽象类中实现，不能获取绑定组件的 `code`，将 `GlobalSettings` 中添加配置 `BACKEND_SERVICE_POLLING_TIMEOUT`

`BACKEND_SERVICE_POLLING_TIMEOUT` 为字典，键为服务类名，值为超时时间

**Comment by neko12583** [comment]
## 功能自测
### 不配置超时时间可正常执行任务
![企业微信截图_20231019193134](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/f20b4bbf-5752-47cb-8e5f-030288fcda70)

### 配置超时时间为1秒超时失败
![企业微信截图_20231019193439](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/15fa4317-b2f6-42b2-bd4c-f5d03182b4e8)
![企业微信截图_20231019195504](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/fc59f39a-d5ba-4f60-a308-914f57a5c7e4)

### 配置超时时间为20秒可正常执行
![企业微信截图_20231023180542](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/2a4c3f6b-a586-4f97-a6fc-93dbb806b698)
