### ISSUE TITLE
feat: 安装 Agent 将上报的 CPU 架构信息更新到 CMDB

### ISSUE THREAD

**Issue by ZhuoZhuoCrayon** [TencentBlueKing/bk-nodeman#1708]
## 背景

> 为什么需要

节点管理可以获取到准确的 CPU 架构信息，需要通过更新主机的方式，写到 CC，供其他平台使用

## 功能

> 你想要什么功能

安装 Agent 将上报的 CPU 架构信息更新到 CMDB

### 建议的方案

![企业微信截图_323ba08f-8c9a-4944-9e73-fd588d03d92b](https://github.com/TencentBlueKing/bk-nodeman/assets/42019787/28191ddc-f85f-4ced-8470-7ead6bb398a3)

根据 CPU 架构信息，将右侧的映射信息，上报到 CC

`x86_64` -> 架构：`x86`、操作系统位数：`64-bit`
`x86` -> 架构：`x86`，操作系统位数：`32-bit`
`aarch64` -> 架构：`arm`，操作系统位数：`arm-64bit`

需要了解的：
* 上报 CPU 架构目前的处理代码：`apps/backend/components/collections/agent_new/install.py Line 792`
* 新增更新 CMDB 字段：找到/熟悉更新接口

![企业微信截图_f9f7436f-85b8-4ba7-94b3-bfaae2f25579](https://github.com/TencentBlueKing/bk-nodeman/assets/42019787/e0b8393f-10f4-49c3-966d-6a5eac1e0565)

* 了解后给出初步技术方案 

### 功能自测

> 代码变更覆盖功能点需要自测并截图

#### 以上三种 case 可以更新到 cc

描述代码变更涉及功能点及自测截图

#### 安装成功、Windows / Linux

描述代码变更涉及功能点及自测截图

**Comment by Huayeaaa** [comment]
### 前置条件
目前上报 CPU 架构的处理方式
![企业微信截图_17071907175974](https://github.com/TencentBlueKing/bk-nodeman/assets/100522884/1516d375-8a51-4689-b306-03218de18c5e)

安装Agent时将日志上报到节点管理后台

后台进行消费并读取（记录）相关所需信息
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/100522884/672e6ed6-3a77-4e07-af2d-094dbaff483e)
后台对相关信息进行变更
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/100522884/39685213-25ca-4f55-b54a-65be62361a7e)

**技术实现**：目前考虑的是在安装完Agent后上报CC
