### ISSUE TITLE
[节点管理-待评审] agent&proxy卸载后在节点管理后仍有记录

### ISSUE THREAD

**Issue by Shutulee** [TencentBlueKing/bk-nodeman#1709]
## 背景

卸载agent / proxy后，状态变为未安装，但主机记录无法被删除。

## 功能

需要提供「从节点管理中移除」的能力。
操作的对象应该是状态为「未安装」的主机记录。

**Comment by ZhuoZhuoCrayon** [comment]
add 的这个场景可以去掉，应该是事件同步的问题
