### ISSUE TITLE
[节点管理-免评审] 节点管理「管控区域」「agent版本」筛选能力优化

### ISSUE THREAD

**Issue by Shutulee** [TencentBlueKing/bk-nodeman#1752]
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/50794209/0df1ecf5-e528-465b-9d41-5408b468a728)

**Comment by Xmandon** [comment]
1. 下拉选择，直接用select选择器组件规范。https://doc.weixin.qq.com/sheet/e3_ACYArgbdAFw0QQWNh0CQZOQ43xgHF?scode=AJEAIQdfAAovq2sJA3ACAAVQbdAFw&tab=BB08J2
2. 只展示本业务相关的管控区域，挺好的，这个在dbm里也需要，看能否复用。

**Comment by EchoQT** [comment]
需求2描述上没有说完整清晰，不是支持『业务下存在的管控区域』，因为页面上可能还有业务以外的其他筛选条件，导致当前的数据范围发生变化，只实现各业务存在的管控区域是不对的，所以其实是要通过当前场景的数据反推下拉框的内容？而且也不只是管控区域，其他的列理应跟管控区域的下拉框渲染逻辑保持一致。

我们是否可以得出这样一个结论？：数据表上的任何字段标题上的下拉式筛选交互都应该只显示当前场景实际存在的数据种类。而不是只针对某一个场景或某一个字段做这种处理。可以跟设计师讨论一下。
