### ISSUE TITLE
[FEATURE] Agent 额外配置目录支持

### ISSUE THREAD

**Issue by ZhuoZhuoCrayon** [TencentBlueKing/bk-nodeman#1756]
## 背景

> 为什么需要

自定义参数放置在额外配置目录下，防止重装 / 配置重载场景下，由于节点管理未感知该特殊配置，而进行覆盖

## 功能

> 你想要什么功能

### 建议的方案

目录格式：

Linux：`/etc/sysconfig/gse/${环境代号，默认为 bk}/user_conf/`
Windows: `C:\\Windows\\System32\\config\\gse\\${环境代号，默认为 bk}\\user_conf`

`/etc/sysconfig/gse/${环境代号，默认为 bk}` 从环境变量 `GSE_ENVIRON_WIN_DIR` 中读取
`C:\\Windows\\System32\\config\\gse\\${环境代号，默认为 bk}` 从环境变量 `GSE_ENVIRON_DIR` 中读取

现状是读取不到时，默认值时空串，此处需要添加默认值

![image](https://github.com/TencentBlueKing/bk-nodeman/assets/42019787/c192d08e-3129-4d09-8890-348a84c83485)

生成命令创建：`apps/backend/agent/solution_maker.py Line 376`

### 功能自测

> 代码变更覆盖功能点需要自测并截图

#### 功能点 1 - Agent （Linux and Windows）安装时，目录自动创建

描述代码变更涉及功能点及自测截图

#### 功能点 2 - 该配置渲染到 Agent（linux & Windows） 配置中的 extra_config_directory 

描述代码变更涉及功能点及自测截图

**Comment by CohleRustW** [comment]
## 步骤

1. 增加企业版默认值兜底未配置环境变量
2. 创建依赖目录时增加 `settings.GSE_ENVIRON_DIR` OR `settings.GSE_ENVIRON_WIN_DIR`
3. 渲染实际的配置 `extra_config_directory `
<img width="1343" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/a33aba9f-92ee-4db6-8861-6795a5af9d87">

**Comment by CohleRustW** [comment]
## 自测
1. 老版本不增加选择依赖和渲染逻辑
<img width="950" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/639fb02a-898a-4d8c-a813-6ab812b10c6d">

<img width="1233" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/2b07c880-d02b-4ba7-ae29-436a4f662298">

2. `gse 2.0`增加渲染逻辑和依赖目录创建

- linux 
<img width="914" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/061cddb4-88f8-4015-ae5a-ecf55516612d">

<img width="1364" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/454766e0-d24a-4eaf-8e34-67814882dd82">

- windows
<img width="649" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/52913239-563d-48c7-af38-e017c4051460">

<img width="802" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/1a665283-dcbe-4edf-b7ba-e0d1cb641d9b">

<img width="1143" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/b4da8e89-2547-4411-b3d8-bea47609496b">

**Comment by CohleRustW** [comment]
### 重载配置测试补充

<img width="1890" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/cb538696-7b1e-4de3-8ea6-52d082fc0f4d">

**Comment by CohleRustW** [comment]
## sprintfix 调整

<img width="867" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/9e8ca0ed-94df-42ed-a36e-63192a38a8fd">
<img width="1322" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/b22fe469-8d18-44e1-b72b-085d0d38678b">
