### ISSUE TITLE
[FEATURE] 2.0 Proxy 支持配置临时文件传输路径

### ISSUE THREAD

**Issue by ZhuoZhuoCrayon** [TencentBlueKing/bk-nodeman#1757]
## 背景

> 为什么需要

大文件传输场景下，/var/ /usr/ 分区空间可能比较小导致磁盘空间满

## 功能

> 你想要什么功能

### 建议的方案

Proxy 的临时文件目录默认放到 `/data/gse${GSE版本}_bkte${Agent实例编号，留空表示0}`

gse${GSE版本}_bkte${Agent实例编号，留空表示0} 从 Agent 安装路径中取，比如 Agent 安装路径为 /usr/local/gse2_test，取 gse2_test

1.0 渲染逻辑：`apps/backend/subscription/steps/agent_adapter/legacy.py Line 473`
2.0 渲染逻辑（需要实现，为了和 1.0 进行区分，2.0 在配置的临时文件目录基础上，加上 file_cache，例如配置路径为 /data/gse2_test，渲染值为 /data/gse2_test/file_cache）：`apps/backend/subscription/steps/agent_adapter/config_context/context_helper.py Line 213`

前端默认值：

前端的默认值是从 ap.agent_config.linux.data_path 中取的，需要修改，可以考虑接入点返回值中，加一个 `file_cache_dirs` 的变量，前端表单默认值从这里取

### 功能自测

> 代码变更覆盖功能点需要自测并截图

#### 功能点 1

描述代码变更涉及功能点及自测截图

#### 功能点 2

描述代码变更涉及功能点及自测截图

**Comment by CohleRustW** [comment]
## 自测

1. 接入点信息
<img width="1193" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/d92470d0-df28-4ddf-8331-104658465348">

2. 安装 `Proxy` 时默认值调整

<img width="2222" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/96ed83b7-36c4-4376-82db-a4f320fe9aa8">

3.  `2.0` 获取安装配置文件
<img width="1231" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/ae57b2b3-2ad7-4eaf-80ba-9c8e49421531">

4. `1.0` 获取安装配置

<img width="948" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/a9a41515-d5eb-417c-aa08-933859b17cea">

<img width="1453" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/a25b69ba-8cd6-4ae4-9253-058af26f3796">

**Comment by wyyalt** [comment]
是否支持配置重载？
