### ISSUE TITLE
[FEATURE] Agent 配置重载功能优化

### ISSUE THREAD

**Issue by ZhuoZhuoCrayon** [TencentBlueKing/bk-nodeman#1769]
## 背景

> 为什么需要

1. 功能缺失：目前仅渲染 Agent 的配置，对于 Proxy 的配置，例如 `gse_data_proxy.conf` `gse_file_proxy.conf` 等却没有渲染下发，不太符合预期

1.0 的 Proxy：
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/42019787/e3c90f54-8014-4504-b37e-b357081d889d)

2.0 的 Proxy：

![image](https://github.com/TencentBlueKing/bk-nodeman/assets/42019787/e97c95af-cac6-4ed2-83ad-d29c5dc01a4f)

3. 2.0 应该是根据 Agent 版本，选择配置模板，如果版本取不到，再取默认版本

## 功能

> 你想要什么功能

1. 补齐配置渲染能力（Proxy 要把所有配置下发下去）
2. 2.0 根据版本来选择模板

### 功能自测

> 代码变更覆盖功能点需要自测并截图

#### 功能点 1

描述代码变更涉及功能点及自测截图

#### 功能点 2

描述代码变更涉及功能点及自测截图

**Comment by wyyalt** [comment]
自测
1.0 proxy
<img width="1871" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/26807891/a84d9dbe-35b6-462b-a191-4cb00d1d5d5e">

2.0 proxy
<img width="1821" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/26807891/18495079-ff55-4294-9f98-93c59787e07f">
