### ISSUE TITLE
[FEATURE] 安装通道兼容多套接入点的场景

### ISSUE THREAD

**Issue by ZhuoZhuoCrayon** [TencentBlueKing/bk-nodeman#1784]
## 背景

> 为什么需要

Agent 1.0 / 2.0 希望复用通道，兼容多套 upstreams

## 功能

> 你想要什么功能

### 建议的方案

不使用 `GseVersion`，而是通过接入点 ID 的方式，标识多套 GSE 环境（`AP-ID-2`）

```json
{
  "dataserver":[
    "127.0.0.1",
    "127.0.0.2"
  ],
  "taskserver":[
    "127.0.0.1",
    "127.0.0.2"
  ],
  "btfileserver":[
    "127.0.0.1",
    "127.0.0.2"
  ],
  "agent_download_proxy":false,
  "channel_proxy_address":"http://127.0.0.1:17981",
  "AP_ID-2":{
    "dataserver":[
      "127.0.0.1",
      "127.0.0.2"
    ],
    "taskserver":[
      "127.0.0.1",
      "127.0.0.2"
    ],
    "btfileserver":[
      "127.0.0.1",
      "127.0.0.2"
    ],
    "agent_download_proxy":false,
    "channel_proxy_address":"http://127.0.0.1:17981"
  }
}
```

![企业微信截图_389c1424-43cf-4905-811d-1974eaa0f13d](https://github.com/TencentBlueKing/bk-nodeman/assets/42019787/a68457f9-8d0f-49be-8db1-efbed88a4b7b)

![企业微信截图_cbda3995-3055-49bf-8c42-d3df92858350](https://github.com/TencentBlueKing/bk-nodeman/assets/42019787/c1d54467-e274-4426-bc0e-d7dffea088b2)

### 功能自测

> 代码变更覆盖功能点需要自测并截图

#### 功能点 1

描述代码变更涉及功能点及自测截图

#### 功能点 2

描述代码变更涉及功能点及自测截图

**Comment by wyyalt** [comment]
自测直连区域
1.0Agent 2.0Agent 安装均符合预期
<img width="1434" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/26807891/a19f84c4-7cb7-4ae7-a70b-24b1998ef52d">
<img width="1699" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/26807891/560a6435-e4b2-4dcf-b1fc-647c6d55f511">
非直连区域
<img width="1750" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/26807891/d25f9b47-fefe-4f72-9d0b-a9afc0f172d0">
<img width="1723" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/26807891/bc60d9e4-5bcb-47a1-81d3-931d50f70811">
