### ISSUE TITLE
[FEATURE] 接入点屏蔽方案

### ISSUE THREAD

**Issue by ZhuoZhuoCrayon** [TencentBlueKing/bk-nodeman#1796]
## 背景

> 为什么需要

腾讯文档

## 功能

> 你想要什么功能

### 功能自测

> 代码变更覆盖功能点需要自测并截图

#### 功能点 1

描述代码变更涉及功能点及自测截图

#### 功能点 2

描述代码变更涉及功能点及自测截图

**Comment by CohleRustW** [comment]
## 后台方案

全局配置表中增加配置项 `ENABLE_AP_VERSION_MUTEX`, 前端通过这个值判断是否进行屏蔽操作

前端交互主要注意两点：

1. 每台主机的选择，当主机当前属于 `1.0` 时不允许选择 `2.0`
2. 批量的选择，涉及到混合的选择就提示报错

**Comment by CohleRustW** [comment]
## 后台自测

<img width="698" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/899cbde7-846d-4dc7-9775-6c7df23df1b1">

**Comment by GONGONGONG** [comment]
前端自测
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/29882448/4d764c27-4d3f-441f-b8c6-c1dc874ec24a)
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/29882448/1487ee22-dfe1-4337-9af5-51747fb291cc)

**Comment by CohleRustW** [comment]
### 联调测试

1. 当前环境打开屏蔽开关以后，只有 `1.0`的接入点时
<img width="954" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/60c3ef41-d417-4926-9c1b-701b4a01c5c2">
<img width="408" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/32032e71-dd17-4c7e-91b1-dffaefbb6a0a">
<img width="362" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/36f64180-b336-408d-9bd5-9775ff7d3f79">

2. `1.0` 和 `2.0` 的接入点混合时
<img width="893" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/ab5e8d2b-7360-447a-9f50-64b561c1a473">

<img width="368" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/40dae5f8-704b-400d-8fe8-28f34686e9b2">
<img width="344" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/874849fb-4b58-4188-aea3-df94ba39a492">
<img width="305" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/838e82a0-4bc0-4475-953a-36fee3376f86">

<img width="273" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/a971c8ff-2436-406c-a0d2-1f7ace77806c">

<img width="353" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/b915354e-d405-4d8d-9891-0a2ef7cc2dad">


3.  开关关闭时，混合场景批量编辑
<img width="420" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/64f9223d-6342-4068-a243-37aa83c80447">
