### ISSUE TITLE
[FEATURE] 提供增量业务自动加入 GSE 2.0 灰度的能力

### ISSUE THREAD

**Issue by ZhuoZhuoCrayon** [TencentBlueKing/bk-nodeman#1805]
## 背景

> 为什么需要

增量业务（新业务走 2.0，需要标记成灰度）

## 功能

> 你想要什么功能

提供增量业务自动加入 GSE 2.0 灰度的能力

### 建议的方案

提供一个 manage 命令，可以传一个 ID 参数（截止到启动 GSE 2.0 切换前，最大的业务 ID），该命令后续通过标准运维定期执行，找到业务 ID 大于该值的业务列表，批量加到灰度列表

`apps/core/gray/handlers.py cls.update_gray_scope_list(validated_data)`

### 功能自测

> 代码变更覆盖功能点需要自测并截图

#### 功能点 1

描述代码变更涉及功能点及自测截图

#### 功能点 2

描述代码变更涉及功能点及自测截图

**Comment by wyyalt** [comment]
可以通过周期任务判断 GlobalSettings.GSE2_GRAY_SCOPE_LIST, 如果存在业务即认为已开始切换，此时GlobalSettings增加一个key记录当前所有业务列表，可以同步主机或者单独增加周期任务进行比对添加

**Comment by ZhuoZhuoCrayon** [comment]
> 可以通过周期任务判断 GlobalSettings.GSE2_GRAY_SCOPE_LIST, 如果存在业务即认为已开始切换，此时GlobalSettings增加一个key记录当前所有业务列表，可以同步主机或者单独增加周期任务进行比对添加

使用周期任务没有问题，但感觉「开始切换」的这个动作可以通过 GlobalSettings 里的「当前所有业务列表」不为空来判断是否需要执行周期任务？

**Comment by wyyalt** [comment]
<img width="929" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/26807891/a6ac1220-c828-45c8-95ce-6f606d4d36f0">
