### ISSUE TITLE
[FEATURE] 安装通道支持隐藏功能

### ISSUE THREAD

**Issue by ZhuoZhuoCrayon** [TencentBlueKing/bk-nodeman#1832]
## 背景

> 为什么需要

部分安装通道属于业务/场景独有，需要「默认隐藏」

## 功能

> 你想要什么功能

列表拉取接口默认隐藏「标记隐藏」的安装通道，指定 「hidden=false」才拉取全部

### 建议的方案

参考下 filterset_fields，应该可以在 Viewset 直接配置下过滤逻辑 

![image](https://github.com/TencentBlueKing/bk-nodeman/assets/42019787/1f7bb400-7985-4c68-8616-c8ba456e5cb7)

### 功能自测

> 代码变更覆盖功能点需要自测并截图

#### 功能点 1

描述代码变更涉及功能点及自测截图

#### 功能点 2

描述代码变更涉及功能点及自测截图

**Comment by CohleRustW** [comment]
# 自测

###  默认不展示隐藏通道
<img width="2597" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/2bd8d42a-065f-4d17-b8fa-6aacae0f0c7d">

### 增加  hidden=false 时展示隐藏通道

<img width="2549" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/851f50d7-616d-423c-9455-b4eee600623e">


###  创建隐藏安装通道
<img width="1111" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/434266ac-8be7-4d3a-85af-6cb6e5697bb5">

### 不指定隐藏参数创建的安装通道不隐藏

<img width="1044" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/c55a9d65-53ab-4999-87e3-056104a50d11">

### 更新安装通道

<img width="1057" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/1fd833c5-61a8-4718-9525-44ccda06b8d2">
<img width="1363" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/3caa6c7f-3aaa-4b60-880c-f46c6219fb04">

**Comment by CohleRustW** [comment]
## sprintfix 自测

<img width="2300" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/cae702e5-8c9b-44af-ad17-4f3016e16dab">

<img width="1742" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/91480c28-0085-4c54-b0f7-d763d984d7fd">

<img width="2294" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/16596c3b-534d-4a01-9bab-62da57d59c8e">

<img width="1159" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/9ed785d7-a5f6-464c-9862-6c8301a0530f">
