### ISSUE TITLE
[OPTIMIZATION] 任务历史筛选条件拉取优化

### ISSUE THREAD

**Issue by wyyalt** [TencentBlueKing/bk-nodeman#1856]
## 背景

> 为什么需要

## 功能

> 你想要什么功能

### 功能自测

> 代码变更覆盖功能点需要自测并截图

#### 功能点 1

描述代码变更涉及功能点及自测截图

#### 功能点 2

描述代码变更涉及功能点及自测截图

**Comment by GONGONGONG** [comment]
前端自测
get改为post
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/29882448/8bba22c4-f098-40e2-b2a9-dbb5bd678ec9)
参数
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/29882448/8a4a6e50-e2d5-43f0-88bf-0806d724dd67)
![企业微信截图_17000133652258](https://github.com/TencentBlueKing/bk-nodeman/assets/29882448/9c64d17d-d0e5-4efa-ad12-dd9e8faf644e)
