### ISSUE TITLE
[FEATURE] 数据清理二期-订阅实例表

### ISSUE THREAD

**Issue by CohleRustW** [TencentBlueKing/bk-nodeman#1896]
## 背景

> 为什么需要

## 功能

> 你想要什么功能

### 建议的方案

1. `is_latest=true` 标识了一个订阅当前所维护的有效实例范围，理论上可以通过清理 `is_latest = false` 的数据，达到比较好的数据清理效果

![企业微信截图_5dca355e-e3e0-4732-b0ba-3d82fc16cf20](https://github.com/TencentBlueKing/bk-nodeman/assets/42019787/66aad300-7119-4e33-a552-b89c0d6c5b20)

2. 顺带清理 `is_latest = false` 关联的 `SubscriptionTask`，及 `SubscriptionTask` 关联的 `PipelineTree`

3. 支持配置清理 xx 天前数据，保留前 xx 天数据，便于排查问题

4. 策略类型的订阅似乎暂时清理不了，虽然 `is_latest=false`，但自动巡检任务会同步到 `Job`，可以评估下清理后页面查看巡检任务的效果，看看UI交互能否接受

5. 整理出数据清理会影响到的接口，便于测试清理逻辑

### 功能自测

> 代码变更覆盖功能点需要自测并截图

#### 功能点 1

描述代码变更涉及功能点及自测截图

#### 功能点 2

描述代码变更涉及功能点及自测截图

**Comment by neko12583** [comment]
## 自测截图

### 清理前数据情况
![instance_record表需清理数据量](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/dc2a3d3e-aa68-4a03-98ff-e1756f070808)

### 清理日志
![开始清理1](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/9cd85d4a-7fcb-4bbf-9a74-2e68dc583052)

![开始清理2](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/1d6e3153-a10f-497d-9c8c-a45f9847fcca)

![开始清理3](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/740d28c4-d25d-49ce-8e88-8074608ba8a1)

### 清理后数据情况

![清理后数据情况](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/5cfd8645-c8c5-4785-9396-f744d3d5d585)


### 清理后页面情况以及接口返回

#### 任务历史页面

![清理后页面任务历史](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/bf615f48-7c6f-4764-800b-acc82f47c72a)


一个月前任务展示以及详情

![一个月前任务展示](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/dac1cb24-ba36-4159-b10f-288f39cce09c)

![一个月前任务详情](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/ac8c5587-6680-4feb-8296-9ec8aadc0d41)

![删除数据后task_result接口返回](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/f4fd8a4a-5c43-4a90-a004-05ee1a7b75a5)
