### ISSUE TITLE
[BUG] 安装预设插件没有过滤已禁用的插件

### ISSUE THREAD

**Issue by ZhuoZhuoCrayon** [TencentBlueKing/bk-nodeman#1909]
## 问题描述

> 简明扼要地描述bug是什么

安装预设插件没有过滤已禁用的插件

![image](https://github.com/TencentBlueKing/bk-nodeman/assets/42019787/817c6a38-fa33-4e66-97fe-adb3cfb1a8c3)

bkbscp 还是被下发了

代码位置：`apps/backend/components/collections/agent_new/install_plugins.py`

### 截屏

请提供截屏来解释你的问题，当然这也能更好地帮助我们理解问题。

### 请提供以下信息

- [x] bk-nodeman 版本 (发布版本号 或 git
  tag)： 
- [ ] 蓝鲸PaaS 版本：
- [ ] bk-nodeman 异常日志：

## 重现方法

> 列出如何重现的方法或操作步骤

1. 转到 '....'
2. 点击 '....'
3. 错误现象 '....'

### 功能自测

> 代码变更覆盖功能点需要自测并截图

#### 功能点 1

描述代码变更涉及功能点及自测截图

#### 功能点 2

描述代码变更涉及功能点及自测截图

**Comment by CohleRustW** [comment]
## 背景

> `Agent`  安装流程
<img width="1010" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/fc6840ae-6889-4bd6-8d86-345d6d4e728e">

[修改位置](https://github.com/TencentBlueKing/bk-nodeman/blob/9d5284f7696a8250b537dfffaec5389ee114f5ab/apps/backend/components/collections/agent_new/install_plugins.py#L25)

[(参考方式)](https://github.com/TencentBlueKing/bk-nodeman/blob/9d5284f7696a8250b537dfffaec5389ee114f5ab/apps/backend/plugin/views.py#L257)

 测试接口
<img width="2731" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/8f887b3c-5a28-43ab-8808-9bf9f4dd5512">

**Comment by Huayeaaa** [comment]
对未启用的插件进行过滤
![企业微信截图_1699336858763](https://github.com/TencentBlueKing/bk-nodeman/assets/100522884/1dd3fc26-b683-46cc-a0e0-55217c1e4a1e)
对过滤条件进行单元测试OK
![企业微信截图_16993369227730](https://github.com/TencentBlueKing/bk-nodeman/assets/100522884/6d9c9f8c-237d-4033-8e53-791b73c0beb3)

**Comment by Huayeaaa** [comment]
对禁用的插件进行过滤后进行的单元测试
![企业微信截图_16993369227730](https://github.com/TencentBlueKing/bk-nodeman/assets/100522884/fe5c4d5f-789e-41a5-9cba-30c9037b3715)
