### ISSUE TITLE
[FEATURE] 优化任务执行过程中目标主机退库导致流程整体失败的场景

### ISSUE THREAD

**Issue by ZhuoZhuoCrayon** [TencentBlueKing/bk-nodeman#1962]
## 背景

> 为什么需要

该问题偶现导致流程全部失败

![image](https://github.com/TencentBlueKing/bk-nodeman/assets/42019787/fb7d1ebf-4c83-4ffc-bdaf-4383fdb35dc5)

## 功能

> 你想要什么功能

优化任务执行过程中目标主机退库的场景，检测到主机退库的场景，单独对这个目标报错

```
[task_engine][service_run_exc_handler:CheckAgentAbilityService] act_name -> 检查Agent功能, exc -> 102710", "exc_info": "Traceback (most recent call last):
 File "/app/apps/utils/exc.py", line 91, in wrapped_executor
 return wrapped(*args, **kwargs)
 File "/app/apps/backend/components/collections/base.py", line 523, in execute
 common_data = self.get_common_data(data)
 File "/app/apps/prometheus/helper.py", line 213, in __call__
 return self.wrapped_executor(wrapped, instance, args, kwargs)
 File "/app/apps/prometheus/helper.py", line 137, in wrapped_executor
 result = wrapped(*args, **kwargs)
 File "/app/apps/backend/components/collections/agent_new/base.py", line 80, in get_common_data
 host = common_data.host_id_obj_map[bk_host_id]
KeyError: 102710
```

### 建议的方案

1. 封装 `host_id__ap_map` `host_id_obj_map`  的 `get` 逻辑，参考（apps.backend.components.collections.plugin.InitProcessStatusService.get_target_host_objs）：
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/42019787/c5279c6c-27d3-40ac-91ce-bc76224f349c)

2. 修改引用到 1. 的逻辑，进行统一封装

3. 差量同步主机，对比快照后可调用：bulk_differential_sync_biz_hosts

### 功能自测

> 代码变更覆盖功能点需要自测并截图

#### 功能点 1

描述代码变更涉及功能点及自测截图

#### 功能点 2

描述代码变更涉及功能点及自测截图

**Comment by ping15** [comment]
## 一
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/76253681/8402138e-f173-4348-bf9d-ca993d3ec83d)
#### 1. 从cc中拉取，将bk_host_ids和host_id_obj_map进行长度的比较，如果bk_host_ids多于host_id_obj_map的话证明有主机被删除
#### 2. 组装expected_bk_host_ids_gby_bk_biz_id，调用bulk_differential_sync_biz_hosts同步主机
#### 3. 再次更新host_id_obj_map

## 二
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/76253681/67bfa0f6-ba9c-41fc-90b6-2e0946b335e7)
#### 1. 遍历时改为common_data.host_id_obj_map.get(bk_host_id)
#### 2. 如果不存在，说明该主机在cc不存在，使用move_insts_to_failed移植到失败实例，并指定content为`该主机在cmdb中不存在`

## 三
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/76253681/b0ce1c80-66f4-45c2-b6ac-67f3674ce3c6)
#### 1. 是否在更新时是否应该处理，失败实例不传入handle_update_db，如果传入，节点管理会新增一台cc不存在的主机
