### ISSUE TITLE
[节点管理-评审会] 主机「复制」按钮支持导出「管控区域 ID:IP」

### ISSUE THREAD

**Issue by ZhuoZhuoCrayon** [TencentBlueKing/bk-nodeman#1963]
## 背景

> 为什么需要

## 功能

> 你想要什么功能

### 功能自测

> 代码变更覆盖功能点需要自测并截图

#### 功能点 1

描述代码变更涉及功能点及自测截图

#### 功能点 2

描述代码变更涉及功能点及自测截图

**Comment by Shutulee** [comment]
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/50794209/a32f799b-2be0-46b5-ba1f-e7a54e6f6633)

**Comment by Shutulee** [comment]
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/50794209/a0eb02a8-a364-4657-b15d-338a6269db85)

**Comment by Shutulee** [comment]
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/50794209/05603ef5-5f78-4959-a643-371595095484)

**Comment by Shutulee** [comment]
<img width="990" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/50794209/743f0808-599f-4290-9ed7-c2f580680a3b">

**Comment by Huayeaaa** [comment]
前端传参
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/100522884/9339cab7-8b6d-4003-83e3-f056a3cdf388)
后端
序列化器增加一个bk_cloud_id_ip字段
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/100522884/9b0104bf-3fc7-4283-971f-87180337d872)
目前对于IPv4的处理
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/100522884/89952811-426f-4d62-8b50-aeb171bdc140)

**Comment by ZhuoZhuoCrayon** [comment]
IPv4 的导出应该有两种形式
* `0:127.0.0.1`
* `0:[127.0.0.1]`

虽然现在只要求导出第一种，后台可以两种都支持下，IPv6 同理

**Comment by Huayeaaa** [comment]
前端传参
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/100522884/d9e35aa8-6213-4394-865f-fdcfeeb3e57d)
后端序列化器
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/100522884/f5c0a91d-20c5-4a0b-b9dc-79b3033e9b68)
后端逻辑
抽函数出来分别对IPv4和IPv6格式进行处理

**Comment by Huayeaaa** [comment]
## 前端方案
### 输出场景
勾选IP：前端自行拼接
所有IP：增加两个子项：管控区域 + IPv4; 管控区域 + IPv6
![企业微信截图_17037568877596](https://github.com/TencentBlueKing/bk-nodeman/assets/100522884/2dec378a-2c6d-46b7-92e8-fe2d8f584cd9)

### 前端传参
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/100522884/1324a449-e5b3-4ec1-8f21-b738d21153af)

### 消费场景
![企业微信截图_17037568958480](https://github.com/TencentBlueKing/bk-nodeman/assets/100522884/72426742-87c8-479c-ba6b-5c01db4dd9e5)
前端需适配携带方括号的场景；
例如  管控区域:ipv4的场景 0:[127.0.0.1];    管控区域:ipv6的场景  0:[0000:0000:0000:0000:0000:ffff:1e00:0001]
### 前端消费场景传参示意
#### 管控区域:ipv4以及管控区域:[ipv4]
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/100522884/13d53d71-47bc-499f-a4f0-cfc90ec5727d)
#### 管控区域:[ipv6]
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/100522884/f3873a00-9090-4b77-b3c1-f0ba10bbbe9f)

**Comment by Huayeaaa** [comment]
### 后端
序列化器增加一个字段和三个返回字段
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/100522884/331cb752-3fd7-4346-8474-48b04092384d)

**视图：** 通过前端传参进行参数解析和数据返回

### 消费场景
对于"[" 和"]"的替换做储存；再构造SQL查询条件。

**Comment by ZhuoZhuoCrayon** [comment]
> ### 后端
> 序列化器增加一个字段以及三个可选项 ![image](https://private-user-images.githubusercontent.com/100522884/293672938-3561f585-420a-4364-84d0-4dc07c008139.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNDUxODksIm5iZiI6MTcwNDI0NDg4OSwicGF0aCI6Ii8xMDA1MjI4ODQvMjkzNjcyOTM4LTM1NjFmNTg1LTQyMGEtNDM2NC04NGQwLTRkYzA3YzAwODEzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwM1QwMTIxMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYzJmZWQ3Yzk1MjE3ZmUwZGE1M2JjMzVmMDQ0YzI4YTI0NjU4MWRmZWM3MTMwYTEzMTI5Y2Q2NWQwNTM1NTExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._IR5icxcNf2mzolR-9dhyyMOxcm2BPn8JEm_YlGqhaA) 视图：通过前端传参进行参数解析和数据提取
> 
> ### 消费场景
> 对于"[" 和"]"的替换做储存；再构造SQL查询条件。

1. `bk_cloud_id_ip` 的作用是？
2. `cloud_ipv6` 应该是「cloud_ipv6_with_brackets」？
