### ISSUE TITLE
[BUG] 非直连场景下 Agent 安装密码查询错误

### ISSUE THREAD

**Issue by ZhuoZhuoCrayon** [TencentBlueKing/bk-nodeman#1966]
## 问题描述

> 简明扼要地描述bug是什么

### 截屏

请提供截屏来解释你的问题，当然这也能更好地帮助我们理解问题。

```
Traceback (most recent call last):
  File "/app/apps/utils/exc.py", line 91, in wrapped_executor
    return wrapped(*args, **kwargs)
  File "/app/apps/backend/components/collections/base.py", line 546, in execute
    return self.run(self._execute, data, parent_data, common_data=common_data)
  File "/app/apps/backend/components/collections/base.py", line 446, in run
    service_func(data, parent_data, **kwargs)
  File "/app/apps/backend/components/collections/agent_new/query_password.py", line 189, in _execute
    inst_id = cloud_ip_map[cloud_ip]["sub_inst_id"]
KeyError: '0-xxx'
```

### 请提供以下信息

- [x] bk-nodeman 版本 (发布版本号 或 git
  tag)： 
- [ ] 蓝鲸PaaS 版本：
- [ ] bk-nodeman 异常日志：

## 重现方法

> 列出如何重现的方法或操作步骤

1. 转到 '....'
2. 点击 '....'
3. 错误现象 '....'

### 建议的修复方案

原因：密码查询逻辑仅支持直连，非直连直接过滤出来报错就可以

### 功能自测

> 代码变更覆盖功能点需要自测并截图

#### 功能点 1

描述代码变更涉及功能点及自测截图

#### 功能点 2

描述代码变更涉及功能点及自测截图

**Comment by ping15** [comment]
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/76253681/8bb3c829-acba-49e8-99bf-e3f79c75b702)
#### 在红框的上一行做个判断，如果说host.bk_cloud_id不等于constants.DEFAULT_CLOUD，移到失败实例中，直接continue

### 单测
#### 继承QueryPasswordFailedTestCase，将主机的云区域设置为constants.DEFAULT_CLOUD + 1，测试是否将这批主机是否被移到失败实例中
#### 继承QueryPasswordFailedTestCase，测试这批主机是否没有被移除到失败实例，且正常流转
