### ISSUE TITLE
[FEATURE] 问题排查常用工具整理(待开发)

### ISSUE THREAD

**Issue by ZhuoZhuoCrayon** [TencentBlueKing/bk-nodeman#1983]
## 背景

> 为什么需要

## 功能

> 你想要什么功能

提供接口 + python manage 命令

1. 订阅部分机器重跑
   * 传递参数：「管控区域ID:IP 列表」（可选）、「主机 ID 列表」（可选）、订阅 ID、是否立刻执行
   * 功能概述：指定订阅的部分机器（或全部）进行重跑

2. 订阅巡检变更测试
  * 在不执行这个订阅巡检的情况下，看下会有什么变更，主要是触发下 make_instances_migrate_actions 看下有没有问题，是否符合预期

### 功能自测

> 代码变更覆盖功能点需要自测并截图

#### 功能点 1

描述代码变更涉及功能点及自测截图

#### 功能点 2

描述代码变更涉及功能点及自测截图

**Comment by CohleRustW** [comment]
> ## 背景
> > 为什么需要
> 
> ## 功能
> > 你想要什么功能
> 
> 提供接口 + python manage 命令
> 
> 1. 订阅部分机器重跑
>    
>    * 传递参数：「管控区域ID:IP 列表」（可选）、「主机 ID 列表」（可选）、订阅 ID、是否立刻执行
>    * 功能概述：指定订阅的部分机器（或全部）进行重跑
> 
> ## 功能实现
> ### 建议的方案
> ### 实现方案
> ### 功能自测
> > 代码变更覆盖功能点需要自测并截图
> 
> #### 功能点 1
> 描述代码变更涉及功能点及自测截图
> 
> #### 功能点 2
> 描述代码变更涉及功能点及自测截图
> 
> #### ...

在不执行这个订阅巡检的情况下，看下会有什么变更，主要是触发下 make_instances_migrate_actions 看下有没有问题，是否符合预期
