### ISSUE TITLE
双栈proxy云区域同时支持ipv4和ipv6单栈pagent的纳管

### ISSUE THREAD

**Issue by ryan-canway** [TencentBlueKing/bk-nodeman#2032]
## 背景

> 同一个云区域下既有ipv4主机也有ipv6主机，需要在同一个云区域下进行2个协议的主机类型进行纳管

## 功能

> proxy支持ipv4和ipv6云区域同时支持ipv4和ipv6单栈pagent的纳管

**Comment by chalice-1831** [comment]
## 背景

当前版本安装pagent，proxy机器为双栈机器，在生成连接配置时即使proxy有v6地址也仍然只会使用ipv4的地址

导致单栈ipv6的pagent无法正常安装

## 方案

针对安装pagent时提供的ip协议栈进行选择

 当仅填写ipv4地址时走proxy的ipv4地址

当仅填写ipv6地址时走proxy的ipv6地址

同时填写ipv4 与 ipv6地址时走proxy ipv4地址

需要保证当pagent使用ipv6地址进行纳管时 proxy必须要有ipv6的地址记录在db中
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/27404133/e5abcb49-65a5-4bbc-b5a3-265993370cde)

涉及后端函数修改`apps/backend/agent/tools.py fetch_gse_servers_info`
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/27404133/4d90aafa-5558-4cc9-a9a8-1e3a1bc5d970)

**Comment by ZhuoZhuoCrayon** [comment]
没毛病，相当于要提供一个方法，根据 P-Agent IP 的协议（v4/v6），对 Proxy 的接入 IP 按协议进行选择，而不是当前代码里的 `v4 or v6` 逻辑（v4 优先）；
判断 v6 / v4 可以用 `/apps/utils/basic.py` 里的 `is_v6` / `is_v4`

**Comment by chalice-1831** [comment]
### 自测

单栈v6安装
![微信截图_20240418111446](https://github.com/TencentBlueKing/bk-nodeman/assets/27404133/01198703-da43-4559-b27d-2a474d47a290)
![微信截图_20240418111519](https://github.com/TencentBlueKing/bk-nodeman/assets/27404133/12584db6-b07b-48ee-b06e-2335a285e761)
proxy:
![微信截图_20240418111314](https://github.com/TencentBlueKing/bk-nodeman/assets/27404133/7ff67d9c-9b83-4300-9e5e-5fc3aaed0117)
pagent:
![微信截图_20240418111345](https://github.com/TencentBlueKing/bk-nodeman/assets/27404133/7ce730b5-38d1-4c87-b535-477a8a3d5326)


双栈安装pagent仍然走之前的v4优先逻辑:
![微信截图_20240418112230](https://github.com/TencentBlueKing/bk-nodeman/assets/27404133/8f668306-61c6-4bbc-a766-11a478fa5852)
