### ISSUE TITLE
[OPTIMIZATION] 安装/重装如果未填写登录IP不记录登录IP字段

### ISSUE THREAD

**Issue by wyyalt** [TencentBlueKing/bk-nodeman#2053]
## 背景

> 为什么需要

## 功能

> 你想要什么功能

### 功能自测

> 代码变更覆盖功能点需要自测并截图

#### 功能点 1

描述代码变更涉及功能点及自测截图

#### 功能点 2

描述代码变更涉及功能点及自测截图

**Comment by ZhuoZhuoCrayon** [comment]
之前存量的数据应该也有这个问题，开发一个工具，可以清理指定业务+管控区域ID的登录 IP

**Comment by ping15** [comment]
### 是否删除(安装时似乎不影响)
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/76253681/29e73062-009f-4d7a-bb84-c9a05066552f)
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/76253681/598fdec9-3509-4fff-bbdf-c39b978c43c1)

### shell安装时查找的ip
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/76253681/dc59cf94-a0a3-4a35-ac08-b5530fce0820)

### batch安装时查找的ip
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/76253681/92ea32d3-ab57-4fd2-aeaa-1717e8a04ed1)
