### ISSUE TITLE
[FEATURE] 通知中心接入

### ISSUE THREAD

**Issue by ZhuoZhuoCrayon** [TencentBlueKing/bk-nodeman#2059]
## 背景

> 为什么需要

## 功能

> 你想要什么功能

### 功能自测

> 代码变更覆盖功能点需要自测并截图

#### 功能点 1

描述代码变更涉及功能点及自测截图

#### 功能点 2

描述代码变更涉及功能点及自测截图

**Comment by wyyalt** [comment]
自测
<img width="1532" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/26807891/3f1c49c8-9acd-4d70-a42f-fd298d8392df">

**Comment by GONGONGONG** [comment]
前端测试范围-全部页面，样例：
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/29882448/810f0716-60d8-4782-aae0-99b974dc3c13)
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/29882448/bdbed13b-15de-4311-8d92-d6c0e40ddafb)
