### ISSUE TITLE
[BUG] 资源配额调整不生效

### ISSUE THREAD

**Issue by ZhuoZhuoCrayon** [TencentBlueKing/bk-nodeman#2099]
## 问题描述

> 简明扼要地描述bug是什么

资源配额调整不生效

### 截屏

请提供截屏来解释你的问题，当然这也能更好地帮助我们理解问题。

### 请提供以下信息

- [x] bk-nodeman 版本 (发布版本号 或 git
  tag)： 
- [ ] 蓝鲸PaaS 版本：
- [ ] bk-nodeman 异常日志：

## 重现方法

> 列出如何重现的方法或操作步骤

1. 在「资源配额」页面调整资源
2. 点击确定后触发任务
3. 在机器上的 .proc / procinfo.json 文件查看，配额不变

### 建议的修复方案

reload 不修改进程配置，资源配置保存后改为重启操作

### 功能自测

> 代码变更覆盖功能点需要自测并截图

#### 功能点 1

描述代码变更涉及功能点及自测截图

#### 功能点 2

描述代码变更涉及功能点及自测截图

**Comment by Huayeaaa** [comment]
根据所提供的修复方案 ；DB变更后，修改其JobType为MAIN_RESTART_PLUGIN
![企业微信截图_17119497029936](https://github.com/TencentBlueKing/bk-nodeman/assets/100522884/977f76bc-9ea2-4830-a665-5140ea656562)
