### ISSUE TITLE
fix: 插件脚本no permission问题

### ISSUE THREAD

**Issue by wyyalt** [TencentBlueKing/bk-nodeman#2137]
## 问题描述

> 简明扼要地描述bug是什么

### 截屏

请提供截屏来解释你的问题，当然这也能更好地帮助我们理解问题。

### 请提供以下信息

- [x] bk-nodeman 版本 (发布版本号 或 git
  tag)： 
- [ ] 蓝鲸PaaS 版本：
- [ ] bk-nodeman 异常日志：

## 重现方法

> 列出如何重现的方法或操作步骤

1. 转到 '....'
2. 点击 '....'
3. 错误现象 '....'

### 功能自测

> 代码变更覆盖功能点需要自测并截图

#### 功能点 1

描述代码变更涉及功能点及自测截图

#### 功能点 2

描述代码变更涉及功能点及自测截图

**Comment by ping15** [comment]
#### 一. `下发脚本`时将脚本下发到根目录tmp目录下【具体实施：将file_target_path修改为根目录下tmp文件夹】
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/76253681/333d21aa-93bd-435e-96fa-18d800863ad9)
#### 二. `初始化操作脚本`时将/tmp/下面所有.sh文件添加-x执行权限【具体实施：修改原有的脚本，将$setup_path修改为根目录tmp文件夹，将tmp下面所有.sh文件添加-x执行权限】
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/76253681/7298ee56-add7-41bd-87ad-7e5578ddfe35)
#### 三. 添加后，将/tmp/下面的.sh文件移到$setup_path/plugins/bin/目录下【具体实施：新增一段脚本，在执行完添加-x执行权限后，将根目录tmp文件夹下面所有.sh文件移到setup_path中】
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/76253681/7298ee56-add7-41bd-87ad-7e5578ddfe35)

### 单测
#### 将apps.backend.tests.components.collections.plugin.utils.JobMockClient.fast_transfer_file进行mock，等test_component执行完之后校验fast_transfer_file的call_args，第一个步骤校验file_target_path，第二三校验script_content

**Comment by ZhuoZhuoCrayon** [comment]
1 - 覆盖问题
之前会触发这个问题的原因，是多个订阅之间传输文件/脚本授权的逻辑会相互覆盖；
这里将脚本放到 /tmp/ 目录下，依然会有这个问题，所以要对分发脚本做订阅级别的隔离，可以加一层目录 `/tmp/plugin_scriptis_sub_{sub_id}`

2 - 拷贝问题

a. 方案里没有给出拷贝到目标目录的方案
b. 拷贝用 `cp` 命令，在 for 里进行，调研下 `cp` 的参数，要用覆盖的模式


3- 自测

a. 模拟 `/plugins/bin/` 无操作脚本的场景
b. 模拟 `/plugins/bin/` 脚本无权限的场景

**Comment by ping15** [comment]
#### get_script_param返回元组，第一个参数为common_data.subscription.id，第二个参数为file_target_path
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/76253681/11eb5ae8-ed0f-41e7-9cfe-2abb78a52442)

![image](https://github.com/TencentBlueKing/bk-nodeman/assets/76253681/a2958dc4-1c90-4071-a545-d3c664d962fa)

#### cp试了一下默认是覆盖模式，但是有个-f选项可以强行覆盖，效果似乎是一样的

![image](https://github.com/TencentBlueKing/bk-nodeman/assets/76253681/42c464ab-a741-4f87-aeee-7d50c7466f8f)

**Comment by ping15** [comment]
#### 一. `下发脚本`时将脚本下发到根目录tmp目录下【具体实施：将file_target_path修改为f"/tmp/plugin_scriptis_sub_{common_data.subscription.id}"】
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/76253681/333d21aa-93bd-435e-96fa-18d800863ad9)
#### 二. `初始化操作脚本`时将/tmp/下面所有.sh文件添加-x执行权限【具体实施：
##### 1. 代码：将return file_target_path修改为return f"/tmp/plugin_scriptis_sub_{common_data.subscription.id} {file_target_path}"
##### 2. 脚本：修改原有的脚本，将$1下面所有.sh文件添加-x执行权限】
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/76253681/82b08c84-2db3-4ff9-ac0c-af22b47588e6)
#### 三. 添加后，将$1下面的.sh文件移到$2目录下【具体实施：脚本for循环里面，在执行完添加-x执行权限后，将文件移到$2中】

修改前的脚本
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/76253681/7298ee56-add7-41bd-87ad-7e5578ddfe35)

修改后的脚本
```bash
#!/bin/bash

setup_path="$2"
tmp_dir="$1"

# 如果没有临时目录，直接返回
if [ ! -d "$tmp_dir" ]; then
  exit 0
fi

# 如果没有复制目标路径，则创建一个
if [ ! -d "$setup_path" ]; then
  mkdir -p "$setup_path"
fi

cd "$tmp_dir"

# tmp_dir路径下的sh文件+x，并复制到setup_path下
for file in $(ls); do
    if echo $file | grep '.*sh$'; then
        chmod +x $tmp_dir/${file}
        cp $tmp_dir/${file} $setup_path/${file} -f
    fi
done
```

### 单测
#### 将apps.backend.tests.components.collections.plugin.utils.JobMockClient.fast_transfer_file进行mock，等test_component执行完之后校验fast_transfer_file的call_args，第一个步骤校验file_target_path，第二三校验script_content
