### ISSUE TITLE
fix: 同步主机差量逻辑修复

### ISSUE THREAD

**Issue by Huayeaaa** [TencentBlueKing/bk-nodeman#2167]
## 问题描述
因转移模块，导致主机在节点管理侧删除记录，

### 截屏
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/100522884/37bd2132-aba5-4cb9-bad9-119daa7804c8)

![企业微信截图_17128278088099(1)](https://github.com/TencentBlueKing/bk-nodeman/assets/100522884/b5150f2d-2e56-4f87-a882-0804168002ea)

### 请提供以下信息
代码位置：apps/node_man/periodic_tasks/sync_cmdb_host.sync_cmdb_host
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/100522884/6ad2e46b-af69-40dd-abde-6c4db28f0ab5)

## 重现方法

> 列出如何重现的方法或操作步骤

1. 转到 '....'
2. 点击 '....'
3. 错误现象 '....'

### 功能自测

> 代码变更覆盖功能点需要自测并截图

#### 功能点 1

描述代码变更涉及功能点及自测截图

#### 功能点 2

描述代码变更涉及功能点及自测截图

**Comment by ZhuoZhuoCrayon** [comment]
1. `need_delete_host_ids` 缓存到 Redis 列表
2. 定时任务定期取出处理（先进先出）

参考：安装日志写入和消费的过程
