### ISSUE TITLE
docs: 蓝盾Agent安装支持手动安装

### ISSUE THREAD

**Issue by wyyalt** [TencentBlueKing/bk-nodeman#2211]
## 背景

> 为什么需要
蓝盾做了一个Agent安装的页面，但只支持远程安装，想要通过节点管理接口，支持手动安装

## 功能

> 你想要什么功能
节点管理本身支持手动安装，梳理其它平台使用节点管理接口实现手动安装的协议，流程

### 功能自测

> 代码变更覆盖功能点需要自测并截图

#### 功能点 1

描述代码变更涉及功能点及自测截图

#### 功能点 2

描述代码变更涉及功能点及自测截图

**Comment by ZhuoZhuoCrayon** [comment]
接口文档放到：https://github.com/TencentBlueKing/bk-nodeman/tree/v2.4.x/docs/apidoc
