### ISSUE TITLE
fix: 同个订阅触发时间相邻导致订阅中实例执行动作变更

### ISSUE THREAD

**Issue by Huayeaaa** [TencentBlueKing/bk-nodeman#2230]
## 问题描述
主动触发的订阅与订阅巡检时间相近，导致用户预期与实际操作结果不一致

**主动触发订阅任务**
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/100522884/321d5ce2-5830-4af2-9d35-da24d2905944)
主动触发的期望是移除配置
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/100522884/a5df13bc-6b71-4be7-a516-e4373f1181cd)

**订阅巡检行为**
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/100522884/97ca912c-1e3c-4d76-a46d-3bee13a0ee42)
订阅巡检行为：检测到这几台实例的配置不存在会推送配置文件
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/100522884/9a3e232e-ed70-4b55-8629-59ee61f3ce00)

导致所期望的UNINSTALL-->INSTALL，后续的页面也操作会沿用最新的INSTALL去下发订阅，导致数据继续上报问题
> 简明扼要地描述bug是什么

### 截屏

请提供截屏来解释你的问题，当然这也能更好地帮助我们理解问题。

### 请提供以下信息

- [x] bk-nodeman 版本 (发布版本号 或 git
  tag)： 
- [ ] 蓝鲸PaaS 版本：
- [ ] bk-nodeman 异常日志：

## 重现方法

> 列出如何重现的方法或操作步骤

1. 转到 '....'
2. 点击 '....'
3. 错误现象 '....'

### 建议的修复方案
目前负责人提供的方案：加锁执行
### 功能自测

> 代码变更覆盖功能点需要自测并截图

#### 功能点 1

描述代码变更涉及功能点及自测截图

#### 功能点 2

描述代码变更涉及功能点及自测截图

**Comment by ZhuoZhuoCrayon** [comment]
相同问题，合并到 #2232
