### ISSUE TITLE
feat: 支持通过环境变量配置 Agent 安装前置脚本

### ISSUE THREAD

**Issue by ZhuoZhuoCrayon** [TencentBlueKing/bk-nodeman#2236]
## 背景

> 为什么需要

## 功能

> 你想要什么功能

支持通过环境变量配置 Agent 安装前置脚本，安装 Agent 时先执行这部分脚本

### 建议的方案

1. 新增环境变量：`BKAPP_SCRIPT_HOOKS`，hook 间使用逗号进行分隔，例如 `active_firewall_policy,firewall_off`
2. 在 /apps/node_man/serializers/job.py InstallSerializer` 进行安装前判断，如果存在环境变量，将内置 hooks 置于已有的 `script_hooks` 前
3. 新增 ieod_active_firewall_policy.bat 到 `apps/core/script_manage/data.py`，增加 `support_cloud_ids`，因为该需求只在直连区域生效

前置脚本执行原理，可参考：https://github.com/TencentBlueKing/bk-nodeman/pull/1195

新增环境变量参考 commit：https://github.com/TencentBlueKing/bk-nodeman/commit/0498ea5442446d20a12552e4c688600ced56ec27

### 功能自测

> 代码变更覆盖功能点需要自测并截图

#### 功能点 1

描述代码变更涉及功能点及自测截图

#### 功能点 2

描述代码变更涉及功能点及自测截图

**Comment by ping15** [comment]
### 1. 将`ieod_active_firewall_policy.bat`放到script_tools/script_manage_tmp/下
### 2. 修改ScriptInfo
```python
@dataclass
class ScriptInfo:
    name: str
    filename: str
    path: str
    description: str
    support_os_list: typing.List[str]

    # 短命令
    oneline: typing.Optional[str] = None
    
    # 支持的云区域
    support_cloud_ids: typing.List[int] = []
```
### 2. apps/core/script_manage/data.py添加IEOD_ACTIVE_FIREWALL_POLICY_SCRIPT_INFO，令support_cloud_ids为[0]
### 3. 修改build_script_hook_steps，for循环遍历self.script_hook_objs时判断
```python
for script_hook_obj in self.script_hook_objs:
    support_cloud_ids: typing.List[int] = script_hook_obj.script_info_obj.support_cloud_ids
    if support_cloud_ids and self.host.bk_cloud_id not in support_cloud_ids:
        continue

    ......
```

### 4. 序列化器调整InstallSerializer的script_hooks，如果有env.BKAPP_SCRIPT_HOOKS，处理并使用作为script_hooks，否则为[]
