### ISSUE TITLE
[FEATURE] 安装Agent后重新下发插件包并安装

### ISSUE THREAD

**Issue by zhangzhw8** [TencentBlueKing/bk-nodeman#303]
**你想要什么功能**
安装Agent后重新下发插件包并安装

**为什么需要**
当前安装Agent后仅托管插件，此插件是打包在Agent包中的，当插件更新后，新安装的Agent包中的插件还是老的，不符合预期

**建议如何实现**
调用作业平台下发插件包后再调用GSE启动插件（成功启动后附带托管效果）

**Comment by ZhuoZhuoCrayon** [comment]
通过子流水线实现 #517
