### ISSUE TITLE
[BUG] 云区域接入点信息变更时存量proxy接入点信息不更新

### ISSUE THREAD

**Issue by zhangzhw8** [TencentBlueKing/bk-nodeman#494]
**问题描述**
云区域接入点信息变更时存量proxy接入点信息不更新

**重现方法**
列出如何重现的方法或操作步骤 
1. 编辑云区域接入点
2. 重装Proxy
3. Proxy仍使用老的接入点

**预期现象**
使用云区域的接入点

接入点选择逻辑

1. 节点类型为PROXY
	- 云区域自动选择 -> 进行探测
	- 云区域非自动选择 -> 直接使用云区域所属接入点
2. 节点类型为PAGENT
	- 使用PROXY所属接入点
3. 节点类型为AGENT
	- 自动选择 -> 进行探测
	- 非自动选择 -> 使用用户选择的接入点

**Comment by ZhuoZhuoCrayon** [comment]
#506 已修复
