### ISSUE TITLE
[FEATURE] 支持通过 Helm Chart 部署节点管理到 Kubernetes

### ISSUE THREAD

**Issue by donallin823** [TencentBlueKing/bk-nodeman#584]
**你想要什么功能**
想咨询一下是否有官方部署的dockerfile和helm方案
**为什么需要**
一键部署正式环境
**建议如何实现**
编写对应的文档

**Comment by ZhuoZhuoCrayon** [comment]
@donallin823 节点管理是 [腾讯蓝鲸智云](https://bk.tencent.com/) 下负责对蓝鲸体系中的GSE Agent进行管理的SaaS，包括状态查询、版本更新、配置管理、健康检查、进程管理功能。

关于蓝鲸容器化：节点管理依赖蓝鲸各个平台的前置部署，请同学留意上方官网的版本更新
关于节点管理容器化部署：计划 3 ～ 4 月份完成，请同学留意 #584 的流转状态

感谢关注！

**Comment by donallin823** [comment]
那我现在想要部署正式环境的话，有没有目前项目里可以执行的流程，简单和我描述一下，方便我现在能部署一套到正式环境

**Comment by donallin823** [comment]
因为只有dev环境的部署方案，看到代码中有些脚本可以用，但是执行一直出错，求简单的描述，方便我先自行写个简单的docker构建脚本
