### ISSUE TITLE
[FEATURE] 插件包描述文件支持定义配置模板填写参数

### ISSUE THREAD

**Issue by ZhuoZhuoCrayon** [TencentBlueKing/bk-nodeman#654]
**你想要什么功能**

**为什么需要**

**建议如何实现**

**Comment by ZhuoZhuoCrayon** [comment]
背景：
为了支持后续接入第三方插件，目前从配置模板解析参数的方式有以下问题：
1. 不能准确描述嵌套变量及类型
2. 暴露内置变量，增加填写成本


和 @zhangzhw8 大佬讨论后，决定在插件包描述文件增加 配置模板参数定义，解决上述问题

**Comment by ZhuoZhuoCrayon** [comment]
![wecom-temp-831f0dc2cb6bc7e9884d83ad02f0933d](https://user-images.githubusercontent.com/42019787/162658328-78c6dcd7-317f-4e25-9405-c3f5d638e6f4.png)

**Comment by ZhuoZhuoCrayon** [comment]
区分自动解析和自定义配置参数：
* 自定义配置参数返回 `from_project_yaml=True`

原因：
* 自动解析配置参数无法**准确**描述变量类型及结构，计划**仅对自定义配置参数**提供表单填写的功能
* 并且对 `from_project_yaml=True` 的 **主配置** 也开放配置参数填写（在此之前，主配置参数不支持填写）

灰度：使用 **部署策略** 进行灰度，该入口使用比例相对较低

```json
{
  "title": "variables",
  "from_project_yaml": true,
  "type": "object",
  "properties": {
    "enabled": {
      "title": "enabled",
      "type": "boolean",
      "_required": false,
      "default": true
    },
    "config_name": {
      "title": "config_name",
      "type": "string"
    },
    "max_timeout": {
      "title": "max_timeout",
      "type": "number",
      "default": 300
    },
    "sleep_time": {
      "title": "sleep_time",
      "type": "number",
      "default": 0.01
    },
    "labels": {
      "title": "labels",
      "type": "array",
      "items": {
        "title": "label",
        "type": "object",
        "_required": false,
        "properties": {}
      }
    },
    "named_labels": {
      "title": "named_labels",
      "type": "array",
      "items": {
        "title": "named_label",
        "type": "object",
        "properties": {
          "name": {
            "title": "name",
            "type": "string",
            "_required": false
          },
          "value": {
            "title": "value",
            "type": "string"
          }
        }
      }
    }
  }
}
```

**Comment by neko12583** [comment]
## 自测
修改 linux-x86_64 插件包，修改 project.yaml 以及 配置模板
![修改linux配置模板](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/a918aa20-35fc-49e1-86d3-75d8bf91040e)

![修改linux-yaml文件](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/c739581b-46a5-46f7-9dda-15e94faa19ab)

修改 windows-x86_64 插件包，修改 project.yaml 以及 配置模板
![修改windows配置模板](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/a2c2bfe3-919c-40ca-9306-2eb6320bccd1)

![修改windows-yaml文件](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/b4ae9627-0f28-4b2c-b8ef-a003289a9484)

==========

导入插件包

![导入插件包](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/e705759c-4c40-4e53-a161-61af57d1f82f)


==========

策略部署插件时，选择对应版本

![选择对应插件版本](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/c8814f23-85ee-4037-ad19-5dfc1d0c304b)

==========

接口返回模板参数信息

![接口返回配置模板参数信息](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/c3ba4a12-1a69-4ebf-aa3b-4fb925a9f62a)

==========

手动调用创建策略接口

![手动调接口脱敏](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/a3f20a8d-fa1e-4a0d-a6a9-0a036bb52f56)


==========

linux-x86_64 机器配置文件渲染情况

![linux配置文件渲染](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/d4229bef-c140-4dcd-b201-1c2d1baa8175)

==========

windows-x86_64 机器配置文件渲染情况

![windows配置文件渲染](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/1f39c5ec-37fc-4fec-9e46-8fbc09b8eb38)

**Comment by neko12583** [comment]
## review 修改后自测

### 任务预览
![任务预览](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/02b90f04-0c90-43d9-9875-e29da42aaf52)

### 安装插件
![安装插件](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/97c2d239-cfb5-46ef-91dc-9057edd49f36)

### 目标机器配置文件渲染情况
![目标机器配置文件渲染情况](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/9c48ee41-8c5c-4319-bf1b-7f9d1848de38)

### 策略部署
![策略部署](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/ab80ac3a-2cdc-49d0-83cc-7d56fa3c7bde)

### 策略部署配置渲染情况
![策略部署配置渲染情况](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/dccfe600-47f3-484c-a8eb-dede1cde349e)

### 任务预览检测配置变化
![任务预览检测配置变化](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/e9e1d014-9504-4bdb-a7c2-e613fe779dac)

**Comment by GONGONGONG** [comment]
### 前端自测
#### 1、无默认值或默认值类型不正确初始化
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/29882448/8ef82c3c-22bf-4e76-95b4-2af3705633b0)
#### 2、数据映射、数组新增和必填校验
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/29882448/1a816873-b803-4baa-a95e-e1a0c135c858)
#### 3、提交数据
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/29882448/7ed54b66-6ecd-45ec-8d5c-1647aa0fa99f)
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/29882448/b3cc0493-6b70-44ff-b419-4960b9556d3e)
#### 4、编辑回填
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/29882448/0c02734c-c759-4473-9355-720a8b1a4464)
####  5、配置为空
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/29882448/f33e00e5-fef0-4b5f-ba71-896729898b72)

**Comment by neko12583** [comment]
## 渲染配置模板时，缺失 control_info 变量问题修复自测

![配置文件增加控制信息](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/82f062d5-3d5f-471c-ac6d-ff63c3393af8)

![下发配置文件效果](https://github.com/TencentBlueKing/bk-nodeman/assets/67174988/b03a2207-42b7-4d00-a6dc-0a349cadc8d0)
