### ISSUE TITLE
[OPTIMIZATION] 手动安装操作指引完善

### ISSUE THREAD

**Issue by ZhuoZhuoCrayon** [TencentBlueKing/bk-nodeman#722]
**你想要什么功能**
![wecom-temp-f28a4b7cc9065f643d930066a4f86e10](https://user-images.githubusercontent.com/42019787/165954017-71a95bd9-be68-427e-9857-aea204474df9.png)

**为什么需要**

手动安装目前存在的问题
* 仅提供安装命令，缺少依赖文件
* 错误的提示：现在的安装命令已经不需要认证信息了
* Windows 直连时，提供 Shell / Bat 两种安装方式

**建议如何实现**

* 方案1：拆分为子步骤，依赖下载 / 安装命令 ...
* 方案2：一行命令
* 根据接入点选择并确定依赖下载命令

**Comment by xyjunco** [comment]
1. 操作命令里已经不需要替换密钥了，不需要蓝色的提示信息了
2. 需要用户执行命令前，先下载一个命令依赖的 setup_proxy.sh 文件，然后再执行命令

**Comment by xyjunco** [comment]
update：

不需要用户单独下载  setup_agent.sh ，合并成一个命令用 && 连起来，一条命令跑完「下载 + 安装」

另外能否把「批量手动安装」的逻辑也合并进来？

**Comment by ZhuoZhuoCrayon** [comment]
1. 提供 shell 、 bat 两种方案
2. 针对 bat 方案提供 curl.exe 的下载指引
   -  所以看起来还是得分步骤，不过针对 Unix，可以一条命令 ｜如果是 Windows ，步骤1就开放文件下载
3. PAgent 应该是在 Proxy 上执行本地安装命令

![WeChatWorkScreenshot_db0bf6e0-1c93-4a0c-9015-7ee9ec5bfc7f](https://user-images.githubusercontent.com/42019787/176819088-d476eab5-506c-469c-a85f-684a0f095324.png)


建议的实现方案：
* 复用 `apps/backend/agent/tools.py gen_commands`
* 重写接口 `apps/node_man/views/job.py get_job_commands`

**Comment by CohleRustW** [comment]
- 安装直连``Unix``
  - 操作系统不需要下载``curl``并且不需要另外下载相关的安装脚本
- 安装直连 ``Windows`` 操作系统需要两步
  - 手动下载``curl.exe``
  - 用户上传成功后不需要单独下载脚本，根据不同的终端执行对应的一键安装命令即可
- 安装``Pagent``
  - 不需要单独下载``setup_pagent.py``, 对应``proxy``机器直接执行全量命令即可
