### ISSUE TITLE
[OPTIMIZATION] 消除运行环境差异

### ISSUE THREAD

**Issue by ZhuoZhuoCrayon** [TencentBlueKing/bk-nodeman#779]
**你想要什么功能**
消除运行环境差异

**为什么需要**
背景：社区版企业版统一

**建议如何实现**
1. 除 gse端口、配置；文档中心链接外，其他代码逻辑分支不再区分 `BkappRunEnvType.CE.value`
2. 版本日志移除 `社区版` 字样

**Comment by CohleRustW** [comment]
处理方案：
  - 当前社区用户接入点信息中新增``gse_client-aix-powerpc.tgz``
  - 证书配置差异不消除

**Comment by CohleRustW** [comment]
追加：
* ``Redis``链接方式差异不消除
* ``solaris``暂不开放
