### ISSUE TITLE
[OPTMIZATION] 重装 Agent 保留 procinfo.json 文件

### ISSUE THREAD

**Issue by ZhuoZhuoCrayon** [TencentBlueKing/bk-nodeman#791]
**你想要什么功能**
重装 Agent 保留 procinfo.json 文件

**为什么需要**
重装 Agent 需要保留 procinfo.json 文件，防止托管进程被干掉

**建议如何实现**
考虑 Proxy  / Agent

**Comment by CohleRustW** [comment]
方案：
> 依然考虑在安装脚本中实现
*  在``remove_agent``时备份文件到``/tmp``目录
* 加锁
* 安装时复制匹配规则的最新的一个文件
* 解锁并删除备份文件

**Comment by CohleRustW** [comment]
方案追加：
> 时效性
  * 选择备份的配置不超过1天
   * 风险：只考虑在重装的场景 而且不存在升级过程中的``gse_agent``升级
**临时方案**
