### ISSUE TITLE
[BUG] 框架依赖环境变量调整错误

### ISSUE THREAD

**Issue by CohleRustW** [TencentBlueKing/bk-nodeman#823]
**问题描述**
在调整``constants.BkappRunEnvType.CE``误将``contants``调整到``settings``前面

**请提供以下信息**

 - [x] bk-nodeman   版本 (发布版本号 或 git tag)： 
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk-nodeman 异常日志：

**Comment by ZhuoZhuoCrayon** [comment]
版本内修复无需 issue
