### ISSUE TITLE
[BUG] 手动安装命令拼接错误

### ISSUE THREAD

**Issue by CohleRustW** [TencentBlueKing/bk-nodeman#854]
**问题描述**
手动安装命令拼接错误

**重现方法**
1. windows 手动安装
2. p-agent手动安装
3. linux手动安装

**预期现象**
拼装正确的手动安装命令

**请提供以下信息**

 - [x] bk-nodeman   版本 (发布版本号 或 git tag)： 
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk-nodeman 异常日志：

**Comment by ZhuoZhuoCrayon** [comment]
重复 #722
