### ISSUE TITLE
[FEATURE] 自监控页面逻辑调整

### ISSUE THREAD

**Issue by xyjunco** [TencentBlueKing/bk-nodeman#885]
**你想要什么功能**

自监控页面 ip 选择的方式需要调整成 「多选 select 框」
现在的样式容易让人产生疑惑，不理解勾选与不勾选的作用

可以考虑直接显示 `状态正常` 或 `状态异常`.

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/4710858/176612869-f3cc3ded-87df-4e5c-9312-0d91023e5442.png">

**Comment by huazai-free** [comment]
后续评审中，Echo姐确认，自监控页面要干掉
