### ISSUE TITLE
[FEATURE] 重装 agent 时保存的密码如果仍在有效期内，需要回显成 *

### ISSUE THREAD

**Issue by xyjunco** [TencentBlueKing/bk-nodeman#905]
**你想要什么功能**

现在系统默认保存了上一次安装机器的密码，且密码在有效期内
展示的效果是密码非必填，而且是空

需要调整成「密码保持必填，同时回显成 ******」

<img width="1726" alt="image" src="https://user-images.githubusercontent.com/4710858/176666680-b76ec558-b205-4b46-bc82-c158343816e0.png">

**Comment by ZhuoZhuoCrayon** [comment]
密码回显 * 号可以根据 identity_info.re_certification 这个字段来判断哈，`false` 表示认证信息未过期
