### ISSUE TITLE
[BUG] 指定安装通道安装 Agent 自动选择接入点报错

### ISSUE THREAD

**Issue by ZhuoZhuoCrayon** [TencentBlueKing/bk-nodeman#949]
**你想要什么功能**

至少不允许安装通道可以自动选择接入点

**为什么需要**

**建议如何实现**

**Comment by CohleRustW** [comment]
之前的方向错误 问题点是出现在选择安装通道的主机在自动选择接入点时，通过节点管理后台去链接了安装通道区域内的主机，按照最低标准，至少不允许安装通道可以自动选择接入点

**Comment by ZhuoZhuoCrayon** [comment]
@GONGONGONG 如果用户指定了安装通道，把 `自动选择` 禁用，默认选中第一个接入点
